# coding: utf-8

"""
    College Basketball Data API

    Use the College Basketball Data API to query game, team, player, recruiting, and analytics data. Request an API key at [CollegeBasketballData.com](https://collegebasketballdata.com/key).

    The version of the OpenAPI document: 1.29.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cbbd.models.team_directory import TeamDirectory  # noqa: E501

class TestTeamDirectory(unittest.TestCase):
    """TeamDirectory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TeamDirectory:
        """Test TeamDirectory
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TeamDirectory`
        """
        model = TeamDirectory()  # noqa: E501
        if include_optional:
            return TeamDirectory(
                season = 1.337,
                season_label = '',
                teams = [
                    cbbd.models.directory_team.DirectoryTeam(
                        id = 1.337, 
                        source_id = '', 
                        school = '', 
                        mascot = '', 
                        abbreviation = '', 
                        display_name = '', 
                        short_display_name = '', 
                        conference_id = 1.337, )
                    ],
                conferences = [
                    cbbd.models.conference.Conference(
                        id = 1.337, 
                        name = '', 
                        abbreviation = '', )
                    ]
            )
        else:
            return TeamDirectory(
                season = 1.337,
                season_label = '',
                teams = [
                    cbbd.models.directory_team.DirectoryTeam(
                        id = 1.337, 
                        source_id = '', 
                        school = '', 
                        mascot = '', 
                        abbreviation = '', 
                        display_name = '', 
                        short_display_name = '', 
                        conference_id = 1.337, )
                    ],
                conferences = [
                    cbbd.models.conference.Conference(
                        id = 1.337, 
                        name = '', 
                        abbreviation = '', )
                    ],
        )
        """

    def testTeamDirectory(self):
        """Test TeamDirectory"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
