# coding: utf-8

"""
    College Basketball Data API

    Use the College Basketball Data API to query game, team, player, recruiting, and analytics data. Request an API key at [CollegeBasketballData.com](https://collegebasketballdata.com/key).

    The version of the OpenAPI document: 1.30.1
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cbbd.models.coverage import Coverage  # noqa: E501

class TestCoverage(unittest.TestCase):
    """Coverage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Coverage:
        """Test Coverage
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Coverage`
        """
        model = Coverage()  # noqa: E501
        if include_optional:
            return Coverage(
                state = 'available',
                reason = 'no_games',
                eligible_games = 1.337,
                covered_games = 1.337
            )
        else:
            return Coverage(
                state = 'available',
                reason = 'no_games',
                eligible_games = 1.337,
                covered_games = 1.337,
        )
        """

    def testCoverage(self):
        """Test Coverage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
