# coding: utf-8

"""
    College Basketball Data API

    Use the College Basketball Data API to query game, team, player, recruiting, and analytics data. Request an API key at [CollegeBasketballData.com](https://collegebasketballdata.com/key).

    The version of the OpenAPI document: 1.29.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cbbd.models.player_season_details_advanced import PlayerSeasonDetailsAdvanced  # noqa: E501

class TestPlayerSeasonDetailsAdvanced(unittest.TestCase):
    """PlayerSeasonDetailsAdvanced unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlayerSeasonDetailsAdvanced:
        """Test PlayerSeasonDetailsAdvanced
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PlayerSeasonDetailsAdvanced`
        """
        model = PlayerSeasonDetailsAdvanced()  # noqa: E501
        if include_optional:
            return PlayerSeasonDetailsAdvanced(
                win_shares = cbbd.models.player_season_details_advanced_win_shares.PlayerSeasonDetails_advanced_winShares(
                    per40 = 1.337, 
                    total = 1.337, 
                    defensive = 1.337, 
                    offensive = 1.337, ),
                porpag = 1.337,
                net_rating = 1.337,
                defensive_rating = 1.337,
                offensive_rating = 1.337,
                games = 1.337
            )
        else:
            return PlayerSeasonDetailsAdvanced(
                win_shares = cbbd.models.player_season_details_advanced_win_shares.PlayerSeasonDetails_advanced_winShares(
                    per40 = 1.337, 
                    total = 1.337, 
                    defensive = 1.337, 
                    offensive = 1.337, ),
                porpag = 1.337,
                net_rating = 1.337,
                defensive_rating = 1.337,
                offensive_rating = 1.337,
                games = 1.337,
        )
        """

    def testPlayerSeasonDetailsAdvanced(self):
        """Test PlayerSeasonDetailsAdvanced"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
