# coding: utf-8

"""
    College Basketball Data API

    Use the College Basketball Data API to query game, team, player, recruiting, and analytics data. Request an API key at [CollegeBasketballData.com](https://collegebasketballdata.com/key).

    The version of the OpenAPI document: 1.28.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cbbd.models.team_stats_leaderboard_unit_stats_field_goals import TeamStatsLeaderboardUnitStatsFieldGoals  # noqa: E501

class TestTeamStatsLeaderboardUnitStatsFieldGoals(unittest.TestCase):
    """TeamStatsLeaderboardUnitStatsFieldGoals unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TeamStatsLeaderboardUnitStatsFieldGoals:
        """Test TeamStatsLeaderboardUnitStatsFieldGoals
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TeamStatsLeaderboardUnitStatsFieldGoals`
        """
        model = TeamStatsLeaderboardUnitStatsFieldGoals()  # noqa: E501
        if include_optional:
            return TeamStatsLeaderboardUnitStatsFieldGoals(
                attempted = 1.337,
                made = 1.337
            )
        else:
            return TeamStatsLeaderboardUnitStatsFieldGoals(
                attempted = 1.337,
                made = 1.337,
        )
        """

    def testTeamStatsLeaderboardUnitStatsFieldGoals(self):
        """Test TeamStatsLeaderboardUnitStatsFieldGoals"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
