# coding: utf-8

"""
    College Basketball Data API

    Use the College Basketball Data API to query game, team, player, recruiting, and analytics data. Request an API key at [CollegeBasketballData.com](https://collegebasketballdata.com/key).

    The version of the OpenAPI document: 1.29.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cbbd.models.team_box_score import TeamBoxScore  # noqa: E501

class TestTeamBoxScore(unittest.TestCase):
    """TeamBoxScore unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TeamBoxScore:
        """Test TeamBoxScore
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TeamBoxScore`
        """
        model = TeamBoxScore()  # noqa: E501
        if include_optional:
            return TeamBoxScore(
                field_goals = cbbd.models.shooting_line.ShootingLine(
                    made = 1.337, 
                    attempted = 1.337, 
                    pct = 1.337, ),
                two_point_field_goals = cbbd.models.shooting_line.ShootingLine(
                    made = 1.337, 
                    attempted = 1.337, 
                    pct = 1.337, ),
                three_point_field_goals = cbbd.models.shooting_line.ShootingLine(
                    made = 1.337, 
                    attempted = 1.337, 
                    pct = 1.337, ),
                free_throws = cbbd.models.shooting_line.ShootingLine(
                    made = 1.337, 
                    attempted = 1.337, 
                    pct = 1.337, ),
                rebounds = cbbd.models.team_box_score_rebounds.TeamBoxScore_rebounds(
                    total = 1.337, 
                    defensive = 1.337, 
                    offensive = 1.337, ),
                assists = 1.337,
                steals = 1.337,
                blocks = 1.337,
                turnovers = 1.337,
                fouls = 1.337,
                minutes = 1.337,
                team_turnovers = 1.337,
                technical_fouls = 1.337,
                flagrant_fouls = 1.337,
                points_in_paint = 1.337,
                points_off_turnovers = 1.337,
                fast_break_points = 1.337,
                true_shooting_pct = 1.337
            )
        else:
            return TeamBoxScore(
                field_goals = cbbd.models.shooting_line.ShootingLine(
                    made = 1.337, 
                    attempted = 1.337, 
                    pct = 1.337, ),
                two_point_field_goals = cbbd.models.shooting_line.ShootingLine(
                    made = 1.337, 
                    attempted = 1.337, 
                    pct = 1.337, ),
                three_point_field_goals = cbbd.models.shooting_line.ShootingLine(
                    made = 1.337, 
                    attempted = 1.337, 
                    pct = 1.337, ),
                free_throws = cbbd.models.shooting_line.ShootingLine(
                    made = 1.337, 
                    attempted = 1.337, 
                    pct = 1.337, ),
                rebounds = cbbd.models.team_box_score_rebounds.TeamBoxScore_rebounds(
                    total = 1.337, 
                    defensive = 1.337, 
                    offensive = 1.337, ),
                assists = 1.337,
                steals = 1.337,
                blocks = 1.337,
                turnovers = 1.337,
                fouls = 1.337,
                minutes = 1.337,
                team_turnovers = 1.337,
                technical_fouls = 1.337,
                flagrant_fouls = 1.337,
                points_in_paint = 1.337,
                points_off_turnovers = 1.337,
                fast_break_points = 1.337,
                true_shooting_pct = 1.337,
        )
        """

    def testTeamBoxScore(self):
        """Test TeamBoxScore"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
