# coding: utf-8

"""
    College Basketball Data API

    This is an API for query various college basketball datasets and analytics. API keys can be acquired by registering on the CollegeBasketballData.com website.

    The version of the OpenAPI document: 1.26.2
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cbbd.models.team_stats_leaderboard_record import TeamStatsLeaderboardRecord  # noqa: E501

class TestTeamStatsLeaderboardRecord(unittest.TestCase):
    """TeamStatsLeaderboardRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TeamStatsLeaderboardRecord:
        """Test TeamStatsLeaderboardRecord
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TeamStatsLeaderboardRecord`
        """
        model = TeamStatsLeaderboardRecord()  # noqa: E501
        if include_optional:
            return TeamStatsLeaderboardRecord(
                season = 56,
                team_id = 56,
                team = '',
                conference = cbbd.models.team_stats_leaderboard_conference.TeamStatsLeaderboardConference(
                    id = 1.337, 
                    abbreviation = '', ),
                record = cbbd.models.team_stats_leaderboard_record_summary.TeamStatsLeaderboardRecordSummary(
                    games = 1.337, 
                    wins = 1.337, 
                    losses = 1.337, ),
                summary = cbbd.models.team_stats_leaderboard_summary.TeamStatsLeaderboardSummary(
                    total_minutes = 1.337, 
                    tracked_shots = 1.337, 
                    pace = 1.337, 
                    raw_net_rating = 1.337, ),
                team_stats = cbbd.models.team_stats_leaderboard_unit_stats.TeamStatsLeaderboardUnitStats(
                    points = cbbd.models.team_stats_leaderboard_unit_stats_points.TeamStatsLeaderboardUnitStats_points(
                        fast_break = 1.337, 
                        off_turnovers = 1.337, 
                        in_paint = 1.337, 
                        total = 1.337, ), 
                    possessions = 1.337, 
                    raw_offensive_rating = 1.337, 
                    true_shooting_pct = 1.337, 
                    effective_field_goal_pct = 1.337, 
                    turnover_ratio = 1.337, 
                    offensive_rebound_pct = 1.337, 
                    free_throw_rate = 1.337, 
                    field_goals = cbbd.models.team_stats_leaderboard_unit_stats_field_goals.TeamStatsLeaderboardUnitStats_fieldGoals(
                        attempted = 1.337, 
                        made = 1.337, ), 
                    two_point_field_goals = cbbd.models.team_stats_leaderboard_unit_stats_field_goals.TeamStatsLeaderboardUnitStats_fieldGoals(
                        attempted = 1.337, 
                        made = 1.337, ), 
                    three_point_field_goals = , 
                    free_throws = , 
                    rebounds = cbbd.models.team_stats_leaderboard_unit_stats_rebounds.TeamStatsLeaderboardUnitStats_rebounds(
                        total = 1.337, 
                        defensive = 1.337, 
                        offensive = 1.337, ), 
                    turnovers = cbbd.models.team_stats_leaderboard_unit_stats_turnovers.TeamStatsLeaderboardUnitStats_turnovers(
                        technical = 1.337, 
                        team = 1.337, 
                        total = 1.337, ), 
                    fouls = cbbd.models.team_stats_leaderboard_unit_stats_fouls.TeamStatsLeaderboardUnitStats_fouls(
                        flagrant = 1.337, 
                        technical = 1.337, 
                        total = 1.337, ), 
                    assists = 1.337, 
                    blocks = 1.337, 
                    steals = 1.337, ),
                opponent_stats = cbbd.models.team_stats_leaderboard_unit_stats.TeamStatsLeaderboardUnitStats(
                    points = cbbd.models.team_stats_leaderboard_unit_stats_points.TeamStatsLeaderboardUnitStats_points(
                        fast_break = 1.337, 
                        off_turnovers = 1.337, 
                        in_paint = 1.337, 
                        total = 1.337, ), 
                    possessions = 1.337, 
                    raw_offensive_rating = 1.337, 
                    true_shooting_pct = 1.337, 
                    effective_field_goal_pct = 1.337, 
                    turnover_ratio = 1.337, 
                    offensive_rebound_pct = 1.337, 
                    free_throw_rate = 1.337, 
                    field_goals = cbbd.models.team_stats_leaderboard_unit_stats_field_goals.TeamStatsLeaderboardUnitStats_fieldGoals(
                        attempted = 1.337, 
                        made = 1.337, ), 
                    two_point_field_goals = cbbd.models.team_stats_leaderboard_unit_stats_field_goals.TeamStatsLeaderboardUnitStats_fieldGoals(
                        attempted = 1.337, 
                        made = 1.337, ), 
                    three_point_field_goals = , 
                    free_throws = , 
                    rebounds = cbbd.models.team_stats_leaderboard_unit_stats_rebounds.TeamStatsLeaderboardUnitStats_rebounds(
                        total = 1.337, 
                        defensive = 1.337, 
                        offensive = 1.337, ), 
                    turnovers = cbbd.models.team_stats_leaderboard_unit_stats_turnovers.TeamStatsLeaderboardUnitStats_turnovers(
                        technical = 1.337, 
                        team = 1.337, 
                        total = 1.337, ), 
                    fouls = cbbd.models.team_stats_leaderboard_unit_stats_fouls.TeamStatsLeaderboardUnitStats_fouls(
                        flagrant = 1.337, 
                        technical = 1.337, 
                        total = 1.337, ), 
                    assists = 1.337, 
                    blocks = 1.337, 
                    steals = 1.337, ),
                shot_profile = cbbd.models.team_stats_leaderboard_shot_profile.TeamStatsLeaderboardShotProfile(
                    assisted_pct = 1.337, 
                    at_rim = cbbd.models.team_stats_leaderboard_shot_profile_at_rim.TeamStatsLeaderboardShotProfile_atRim(
                        assisted_pct = 1.337, 
                        pct = 1.337, 
                        rate = 1.337, ), 
                    dunk = cbbd.models.team_stats_leaderboard_shot_profile_dunk.TeamStatsLeaderboardShotProfile_dunk(
                        rate = 1.337, 
                        assisted = 1.337, 
                        made = 1.337, 
                        attempts = 1.337, ), 
                    layup = cbbd.models.team_stats_leaderboard_shot_profile_dunk.TeamStatsLeaderboardShotProfile_dunk(
                        rate = 1.337, 
                        assisted = 1.337, 
                        made = 1.337, 
                        attempts = 1.337, ), 
                    tip_in = cbbd.models.team_stats_leaderboard_shot_profile_tip_in.TeamStatsLeaderboardShotProfile_tipIn(
                        rate = 1.337, 
                        made = 1.337, 
                        attempts = 1.337, ), 
                    two_point_jumper = cbbd.models.team_stats_leaderboard_shot_profile_two_point_jumper.TeamStatsLeaderboardShotProfile_twoPointJumper(
                        assisted_pct = 1.337, 
                        pct = 1.337, 
                        rate = 1.337, 
                        assisted = 1.337, 
                        made = 1.337, 
                        attempts = 1.337, ), 
                    three_point_jumper = cbbd.models.team_stats_leaderboard_shot_profile_two_point_jumper.TeamStatsLeaderboardShotProfile_twoPointJumper(
                        assisted_pct = 1.337, 
                        pct = 1.337, 
                        rate = 1.337, 
                        assisted = 1.337, 
                        made = 1.337, 
                        attempts = 1.337, ), 
                    free_throws = cbbd.models.team_stats_leaderboard_shot_profile_free_throws.TeamStatsLeaderboardShotProfile_freeThrows(
                        rate = 1.337, 
                        made = 1.337, 
                        attempts = 1.337, ), 
                    distribution = cbbd.models.team_stats_leaderboard_shot_profile_distribution.TeamStatsLeaderboardShotProfile_distribution(
                        three_rate = 1.337, 
                        jumper_rate = 1.337, 
                        midrange_rate = 1.337, ), ),
                adjusted_efficiency = cbbd.models.team_leaderboard_adjusted_efficiency.TeamLeaderboardAdjustedEfficiency(
                    offensive_rating = 1.337, 
                    defensive_rating = 1.337, 
                    net_rating = 1.337, 
                    rankings = cbbd.models.team_leaderboard_adjusted_efficiency_rankings.TeamLeaderboardAdjustedEfficiency_rankings(
                        net = 1.337, 
                        defense = 1.337, 
                        offense = 1.337, ), )
            )
        else:
            return TeamStatsLeaderboardRecord(
                season = 56,
                team_id = 56,
                team = '',
                conference = cbbd.models.team_stats_leaderboard_conference.TeamStatsLeaderboardConference(
                    id = 1.337, 
                    abbreviation = '', ),
                record = cbbd.models.team_stats_leaderboard_record_summary.TeamStatsLeaderboardRecordSummary(
                    games = 1.337, 
                    wins = 1.337, 
                    losses = 1.337, ),
                summary = cbbd.models.team_stats_leaderboard_summary.TeamStatsLeaderboardSummary(
                    total_minutes = 1.337, 
                    tracked_shots = 1.337, 
                    pace = 1.337, 
                    raw_net_rating = 1.337, ),
                team_stats = cbbd.models.team_stats_leaderboard_unit_stats.TeamStatsLeaderboardUnitStats(
                    points = cbbd.models.team_stats_leaderboard_unit_stats_points.TeamStatsLeaderboardUnitStats_points(
                        fast_break = 1.337, 
                        off_turnovers = 1.337, 
                        in_paint = 1.337, 
                        total = 1.337, ), 
                    possessions = 1.337, 
                    raw_offensive_rating = 1.337, 
                    true_shooting_pct = 1.337, 
                    effective_field_goal_pct = 1.337, 
                    turnover_ratio = 1.337, 
                    offensive_rebound_pct = 1.337, 
                    free_throw_rate = 1.337, 
                    field_goals = cbbd.models.team_stats_leaderboard_unit_stats_field_goals.TeamStatsLeaderboardUnitStats_fieldGoals(
                        attempted = 1.337, 
                        made = 1.337, ), 
                    two_point_field_goals = cbbd.models.team_stats_leaderboard_unit_stats_field_goals.TeamStatsLeaderboardUnitStats_fieldGoals(
                        attempted = 1.337, 
                        made = 1.337, ), 
                    three_point_field_goals = , 
                    free_throws = , 
                    rebounds = cbbd.models.team_stats_leaderboard_unit_stats_rebounds.TeamStatsLeaderboardUnitStats_rebounds(
                        total = 1.337, 
                        defensive = 1.337, 
                        offensive = 1.337, ), 
                    turnovers = cbbd.models.team_stats_leaderboard_unit_stats_turnovers.TeamStatsLeaderboardUnitStats_turnovers(
                        technical = 1.337, 
                        team = 1.337, 
                        total = 1.337, ), 
                    fouls = cbbd.models.team_stats_leaderboard_unit_stats_fouls.TeamStatsLeaderboardUnitStats_fouls(
                        flagrant = 1.337, 
                        technical = 1.337, 
                        total = 1.337, ), 
                    assists = 1.337, 
                    blocks = 1.337, 
                    steals = 1.337, ),
                opponent_stats = cbbd.models.team_stats_leaderboard_unit_stats.TeamStatsLeaderboardUnitStats(
                    points = cbbd.models.team_stats_leaderboard_unit_stats_points.TeamStatsLeaderboardUnitStats_points(
                        fast_break = 1.337, 
                        off_turnovers = 1.337, 
                        in_paint = 1.337, 
                        total = 1.337, ), 
                    possessions = 1.337, 
                    raw_offensive_rating = 1.337, 
                    true_shooting_pct = 1.337, 
                    effective_field_goal_pct = 1.337, 
                    turnover_ratio = 1.337, 
                    offensive_rebound_pct = 1.337, 
                    free_throw_rate = 1.337, 
                    field_goals = cbbd.models.team_stats_leaderboard_unit_stats_field_goals.TeamStatsLeaderboardUnitStats_fieldGoals(
                        attempted = 1.337, 
                        made = 1.337, ), 
                    two_point_field_goals = cbbd.models.team_stats_leaderboard_unit_stats_field_goals.TeamStatsLeaderboardUnitStats_fieldGoals(
                        attempted = 1.337, 
                        made = 1.337, ), 
                    three_point_field_goals = , 
                    free_throws = , 
                    rebounds = cbbd.models.team_stats_leaderboard_unit_stats_rebounds.TeamStatsLeaderboardUnitStats_rebounds(
                        total = 1.337, 
                        defensive = 1.337, 
                        offensive = 1.337, ), 
                    turnovers = cbbd.models.team_stats_leaderboard_unit_stats_turnovers.TeamStatsLeaderboardUnitStats_turnovers(
                        technical = 1.337, 
                        team = 1.337, 
                        total = 1.337, ), 
                    fouls = cbbd.models.team_stats_leaderboard_unit_stats_fouls.TeamStatsLeaderboardUnitStats_fouls(
                        flagrant = 1.337, 
                        technical = 1.337, 
                        total = 1.337, ), 
                    assists = 1.337, 
                    blocks = 1.337, 
                    steals = 1.337, ),
                shot_profile = cbbd.models.team_stats_leaderboard_shot_profile.TeamStatsLeaderboardShotProfile(
                    assisted_pct = 1.337, 
                    at_rim = cbbd.models.team_stats_leaderboard_shot_profile_at_rim.TeamStatsLeaderboardShotProfile_atRim(
                        assisted_pct = 1.337, 
                        pct = 1.337, 
                        rate = 1.337, ), 
                    dunk = cbbd.models.team_stats_leaderboard_shot_profile_dunk.TeamStatsLeaderboardShotProfile_dunk(
                        rate = 1.337, 
                        assisted = 1.337, 
                        made = 1.337, 
                        attempts = 1.337, ), 
                    layup = cbbd.models.team_stats_leaderboard_shot_profile_dunk.TeamStatsLeaderboardShotProfile_dunk(
                        rate = 1.337, 
                        assisted = 1.337, 
                        made = 1.337, 
                        attempts = 1.337, ), 
                    tip_in = cbbd.models.team_stats_leaderboard_shot_profile_tip_in.TeamStatsLeaderboardShotProfile_tipIn(
                        rate = 1.337, 
                        made = 1.337, 
                        attempts = 1.337, ), 
                    two_point_jumper = cbbd.models.team_stats_leaderboard_shot_profile_two_point_jumper.TeamStatsLeaderboardShotProfile_twoPointJumper(
                        assisted_pct = 1.337, 
                        pct = 1.337, 
                        rate = 1.337, 
                        assisted = 1.337, 
                        made = 1.337, 
                        attempts = 1.337, ), 
                    three_point_jumper = cbbd.models.team_stats_leaderboard_shot_profile_two_point_jumper.TeamStatsLeaderboardShotProfile_twoPointJumper(
                        assisted_pct = 1.337, 
                        pct = 1.337, 
                        rate = 1.337, 
                        assisted = 1.337, 
                        made = 1.337, 
                        attempts = 1.337, ), 
                    free_throws = cbbd.models.team_stats_leaderboard_shot_profile_free_throws.TeamStatsLeaderboardShotProfile_freeThrows(
                        rate = 1.337, 
                        made = 1.337, 
                        attempts = 1.337, ), 
                    distribution = cbbd.models.team_stats_leaderboard_shot_profile_distribution.TeamStatsLeaderboardShotProfile_distribution(
                        three_rate = 1.337, 
                        jumper_rate = 1.337, 
                        midrange_rate = 1.337, ), ),
                adjusted_efficiency = cbbd.models.team_leaderboard_adjusted_efficiency.TeamLeaderboardAdjustedEfficiency(
                    offensive_rating = 1.337, 
                    defensive_rating = 1.337, 
                    net_rating = 1.337, 
                    rankings = cbbd.models.team_leaderboard_adjusted_efficiency_rankings.TeamLeaderboardAdjustedEfficiency_rankings(
                        net = 1.337, 
                        defense = 1.337, 
                        offense = 1.337, ), ),
        )
        """

    def testTeamStatsLeaderboardRecord(self):
        """Test TeamStatsLeaderboardRecord"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
