# coding: utf-8

"""
    College Basketball Data API

    This is an API for query various college basketball datasets and analytics. API keys can be acquired by registering on the CollegeBasketballData.com website.

    The version of the OpenAPI document: 1.26.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cbbd.models.team_stats_leaderboard_shot_profile import TeamStatsLeaderboardShotProfile  # noqa: E501

class TestTeamStatsLeaderboardShotProfile(unittest.TestCase):
    """TeamStatsLeaderboardShotProfile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TeamStatsLeaderboardShotProfile:
        """Test TeamStatsLeaderboardShotProfile
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TeamStatsLeaderboardShotProfile`
        """
        model = TeamStatsLeaderboardShotProfile()  # noqa: E501
        if include_optional:
            return TeamStatsLeaderboardShotProfile(
                assisted_pct = 1.337,
                at_rim = cbbd.models.team_stats_leaderboard_shot_profile_at_rim.TeamStatsLeaderboardShotProfile_atRim(
                    assisted_pct = 1.337, 
                    pct = 1.337, 
                    rate = 1.337, ),
                dunk = cbbd.models.team_stats_leaderboard_shot_profile_dunk.TeamStatsLeaderboardShotProfile_dunk(
                    rate = 1.337, 
                    assisted = 1.337, 
                    made = 1.337, 
                    attempts = 1.337, ),
                layup = cbbd.models.team_stats_leaderboard_shot_profile_dunk.TeamStatsLeaderboardShotProfile_dunk(
                    rate = 1.337, 
                    assisted = 1.337, 
                    made = 1.337, 
                    attempts = 1.337, ),
                tip_in = cbbd.models.team_stats_leaderboard_shot_profile_tip_in.TeamStatsLeaderboardShotProfile_tipIn(
                    rate = 1.337, 
                    made = 1.337, 
                    attempts = 1.337, ),
                two_point_jumper = cbbd.models.team_stats_leaderboard_shot_profile_two_point_jumper.TeamStatsLeaderboardShotProfile_twoPointJumper(
                    assisted_pct = 1.337, 
                    pct = 1.337, 
                    rate = 1.337, 
                    assisted = 1.337, 
                    made = 1.337, 
                    attempts = 1.337, ),
                three_point_jumper = cbbd.models.team_stats_leaderboard_shot_profile_two_point_jumper.TeamStatsLeaderboardShotProfile_twoPointJumper(
                    assisted_pct = 1.337, 
                    pct = 1.337, 
                    rate = 1.337, 
                    assisted = 1.337, 
                    made = 1.337, 
                    attempts = 1.337, ),
                free_throws = cbbd.models.team_stats_leaderboard_shot_profile_free_throws.TeamStatsLeaderboardShotProfile_freeThrows(
                    rate = 1.337, 
                    made = 1.337, 
                    attempts = 1.337, ),
                distribution = cbbd.models.team_stats_leaderboard_shot_profile_distribution.TeamStatsLeaderboardShotProfile_distribution(
                    three_rate = 1.337, 
                    jumper_rate = 1.337, 
                    midrange_rate = 1.337, )
            )
        else:
            return TeamStatsLeaderboardShotProfile(
                assisted_pct = 1.337,
                at_rim = cbbd.models.team_stats_leaderboard_shot_profile_at_rim.TeamStatsLeaderboardShotProfile_atRim(
                    assisted_pct = 1.337, 
                    pct = 1.337, 
                    rate = 1.337, ),
                dunk = cbbd.models.team_stats_leaderboard_shot_profile_dunk.TeamStatsLeaderboardShotProfile_dunk(
                    rate = 1.337, 
                    assisted = 1.337, 
                    made = 1.337, 
                    attempts = 1.337, ),
                layup = cbbd.models.team_stats_leaderboard_shot_profile_dunk.TeamStatsLeaderboardShotProfile_dunk(
                    rate = 1.337, 
                    assisted = 1.337, 
                    made = 1.337, 
                    attempts = 1.337, ),
                tip_in = cbbd.models.team_stats_leaderboard_shot_profile_tip_in.TeamStatsLeaderboardShotProfile_tipIn(
                    rate = 1.337, 
                    made = 1.337, 
                    attempts = 1.337, ),
                two_point_jumper = cbbd.models.team_stats_leaderboard_shot_profile_two_point_jumper.TeamStatsLeaderboardShotProfile_twoPointJumper(
                    assisted_pct = 1.337, 
                    pct = 1.337, 
                    rate = 1.337, 
                    assisted = 1.337, 
                    made = 1.337, 
                    attempts = 1.337, ),
                three_point_jumper = cbbd.models.team_stats_leaderboard_shot_profile_two_point_jumper.TeamStatsLeaderboardShotProfile_twoPointJumper(
                    assisted_pct = 1.337, 
                    pct = 1.337, 
                    rate = 1.337, 
                    assisted = 1.337, 
                    made = 1.337, 
                    attempts = 1.337, ),
                free_throws = cbbd.models.team_stats_leaderboard_shot_profile_free_throws.TeamStatsLeaderboardShotProfile_freeThrows(
                    rate = 1.337, 
                    made = 1.337, 
                    attempts = 1.337, ),
                distribution = cbbd.models.team_stats_leaderboard_shot_profile_distribution.TeamStatsLeaderboardShotProfile_distribution(
                    three_rate = 1.337, 
                    jumper_rate = 1.337, 
                    midrange_rate = 1.337, ),
        )
        """

    def testTeamStatsLeaderboardShotProfile(self):
        """Test TeamStatsLeaderboardShotProfile"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
