# coding: utf-8

"""
    College Basketball Data API

    This is an API for query various college basketball datasets and analytics. API keys can be acquired by registering on the CollegeBasketballData.com website.

    The version of the OpenAPI document: 1.26.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cbbd.models.team_stats_leaderboard_unit_stats_points import TeamStatsLeaderboardUnitStatsPoints  # noqa: E501

class TestTeamStatsLeaderboardUnitStatsPoints(unittest.TestCase):
    """TeamStatsLeaderboardUnitStatsPoints unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TeamStatsLeaderboardUnitStatsPoints:
        """Test TeamStatsLeaderboardUnitStatsPoints
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TeamStatsLeaderboardUnitStatsPoints`
        """
        model = TeamStatsLeaderboardUnitStatsPoints()  # noqa: E501
        if include_optional:
            return TeamStatsLeaderboardUnitStatsPoints(
                fast_break = 1.337,
                off_turnovers = 1.337,
                in_paint = 1.337,
                total = 1.337
            )
        else:
            return TeamStatsLeaderboardUnitStatsPoints(
                fast_break = 1.337,
                off_turnovers = 1.337,
                in_paint = 1.337,
                total = 1.337,
        )
        """

    def testTeamStatsLeaderboardUnitStatsPoints(self):
        """Test TeamStatsLeaderboardUnitStatsPoints"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
