# coding: utf-8

"""
    College Basketball Data API

    Use the College Basketball Data API to query game, team, player, recruiting, and analytics data. Request an API key at [CollegeBasketballData.com](https://collegebasketballdata.com/key).

    The version of the OpenAPI document: 1.30.1
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cbbd.models.team_season_overview_team import TeamSeasonOverviewTeam  # noqa: E501

class TestTeamSeasonOverviewTeam(unittest.TestCase):
    """TeamSeasonOverviewTeam unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TeamSeasonOverviewTeam:
        """Test TeamSeasonOverviewTeam
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TeamSeasonOverviewTeam`
        """
        model = TeamSeasonOverviewTeam()  # noqa: E501
        if include_optional:
            return TeamSeasonOverviewTeam(
                conference = cbbd.models.conference.Conference(
                    id = 1.337, 
                    name = '', 
                    abbreviation = '', ),
                source_id = '',
                mascot = '',
                school = ''
            )
        else:
            return TeamSeasonOverviewTeam(
                conference = cbbd.models.conference.Conference(
                    id = 1.337, 
                    name = '', 
                    abbreviation = '', ),
                source_id = '',
                mascot = '',
                school = '',
        )
        """

    def testTeamSeasonOverviewTeam(self):
        """Test TeamSeasonOverviewTeam"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
