# coding: utf-8

"""
    College Basketball Data API

    This is an API for query various college basketball datasets and analytics. API keys can be acquired by registering on the CollegeBasketballData.com website.

    The version of the OpenAPI document: 1.27.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cbbd.models.team_leaderboard_adjusted_efficiency import TeamLeaderboardAdjustedEfficiency  # noqa: E501

class TestTeamLeaderboardAdjustedEfficiency(unittest.TestCase):
    """TeamLeaderboardAdjustedEfficiency unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TeamLeaderboardAdjustedEfficiency:
        """Test TeamLeaderboardAdjustedEfficiency
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TeamLeaderboardAdjustedEfficiency`
        """
        model = TeamLeaderboardAdjustedEfficiency()  # noqa: E501
        if include_optional:
            return TeamLeaderboardAdjustedEfficiency(
                offensive_rating = 1.337,
                defensive_rating = 1.337,
                net_rating = 1.337,
                rankings = cbbd.models.team_leaderboard_adjusted_efficiency_rankings.TeamLeaderboardAdjustedEfficiency_rankings(
                    net = 1.337, 
                    defense = 1.337, 
                    offense = 1.337, )
            )
        else:
            return TeamLeaderboardAdjustedEfficiency(
                offensive_rating = 1.337,
                defensive_rating = 1.337,
                net_rating = 1.337,
                rankings = cbbd.models.team_leaderboard_adjusted_efficiency_rankings.TeamLeaderboardAdjustedEfficiency_rankings(
                    net = 1.337, 
                    defense = 1.337, 
                    offense = 1.337, ),
        )
        """

    def testTeamLeaderboardAdjustedEfficiency(self):
        """Test TeamLeaderboardAdjustedEfficiency"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
