# coding: utf-8

"""
    College Basketball Data API

    Use the College Basketball Data API to query game, team, player, recruiting, and analytics data. Request an API key at [CollegeBasketballData.com](https://collegebasketballdata.com/key).

    The version of the OpenAPI document: 1.30.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cbbd.models.team_season_overview import TeamSeasonOverview  # noqa: E501

class TestTeamSeasonOverview(unittest.TestCase):
    """TeamSeasonOverview unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TeamSeasonOverview:
        """Test TeamSeasonOverview
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TeamSeasonOverview`
        """
        model = TeamSeasonOverview()  # noqa: E501
        if include_optional:
            return TeamSeasonOverview(
                format_version = 1,
                team_id = 1.337,
                season = 1.337,
                season_label = '',
                generated_at = '',
                team = cbbd.models.team_season_overview_team.TeamSeasonOverview_team(
                    conference = cbbd.models.conference.Conference(
                        id = 1.337, 
                        name = '', 
                        abbreviation = '', ), 
                    source_id = '', 
                    mascot = '', 
                    school = '', ),
                record = cbbd.models.team_season_overview_record.TeamSeasonOverview_record(
                    unknown_conference_games = 1.337, 
                    unknown_eligibility_games = 1.337, 
                    complete = True, 
                    conference = cbbd.models.count_record.CountRecord(
                        games = 1.337, 
                        wins = 1.337, 
                        losses = 1.337, 
                        unresolved = 1.337, ), 
                    overall = cbbd.models.count_record.CountRecord(
                        games = 1.337, 
                        wins = 1.337, 
                        losses = 1.337, 
                        unresolved = 1.337, ), ),
                ratings = cbbd.models.team_season_overview_ratings.TeamSeasonOverview_ratings(
                    polls = cbbd.models.team_season_overview_ratings_polls.TeamSeasonOverview_ratings_polls(
                        coaches = cbbd.models.poll_standing.PollStanding(
                            state = 'ranked', 
                            date = '', 
                            week = 1.337, 
                            season_type = 'regular', 
                            rank = 1.337, ), 
                        ap = cbbd.models.poll_standing.PollStanding(
                            state = 'ranked', 
                            date = '', 
                            week = 1.337, 
                            season_type = 'regular', 
                            rank = 1.337, ), ), 
                    srs = 1.337, 
                    elo = 1.337, 
                    adjusted = null, ),
                efficiency = cbbd.models.team_season_overview_efficiency.TeamSeasonOverview_efficiency(
                    defense = cbbd.models.unit_metrics.UnitMetrics(
                        box_score = cbbd.models.team_box_score.TeamBoxScore(
                            field_goals = cbbd.models.shooting_line.ShootingLine(
                                made = 1.337, 
                                attempted = 1.337, 
                                pct = 1.337, ), 
                            two_point_field_goals = cbbd.models.shooting_line.ShootingLine(
                                made = 1.337, 
                                attempted = 1.337, 
                                pct = 1.337, ), 
                            three_point_field_goals = , 
                            free_throws = , 
                            rebounds = cbbd.models.team_box_score_rebounds.TeamBoxScore_rebounds(
                                total = 1.337, 
                                defensive = 1.337, 
                                offensive = 1.337, ), 
                            assists = 1.337, 
                            steals = 1.337, 
                            blocks = 1.337, 
                            turnovers = 1.337, 
                            fouls = 1.337, 
                            minutes = 1.337, 
                            team_turnovers = 1.337, 
                            technical_fouls = 1.337, 
                            flagrant_fouls = 1.337, 
                            points_in_paint = 1.337, 
                            points_off_turnovers = 1.337, 
                            fast_break_points = 1.337, 
                            true_shooting_pct = 1.337, ), 
                        points = 1.337, 
                        possessions = 1.337, 
                        raw_rating = 1.337, 
                        effective_field_goal_pct = 1.337, 
                        turnover_pct = 1.337, 
                        offensive_rebound_pct = 1.337, 
                        free_throw_rate = 1.337, ), 
                    offense = cbbd.models.unit_metrics.UnitMetrics(
                        points = 1.337, 
                        possessions = 1.337, 
                        raw_rating = 1.337, 
                        effective_field_goal_pct = 1.337, 
                        turnover_pct = 1.337, 
                        offensive_rebound_pct = 1.337, 
                        free_throw_rate = 1.337, ), 
                    pace_games = 1.337, 
                    pace = 1.337, 
                    coverage = cbbd.models.coverage.Coverage(
                        state = 'available', 
                        reason = null, 
                        eligible_games = 1.337, 
                        covered_games = 1.337, ), ),
                shooting = cbbd.models.team_season_overview_shooting.TeamSeasonOverview_shooting(
                    buckets = [
                        cbbd.models.shot_bucket.ShotBucket(
                            key = 'at_rim', 
                            attempts = 1.337, 
                            made = 1.337, 
                            attempt_pct = 1.337, 
                            field_goal_pct = 1.337, )
                        ], 
                    tracked_attempts = 1.337, 
                    coverage = cbbd.models.coverage.Coverage(
                        state = 'available', 
                        reason = null, 
                        eligible_games = 1.337, 
                        covered_games = 1.337, ), ),
                players = cbbd.models.team_season_overview_players.TeamSeasonOverview_players(
                    rows = [
                        cbbd.models.profile_player.ProfilePlayer(
                            season_stats = cbbd.models.player_season_details.PlayerSeasonDetails(
                                field_goals = cbbd.models.shooting_line.ShootingLine(
                                    made = 1.337, 
                                    attempted = 1.337, 
                                    pct = 1.337, ), 
                                two_point_field_goals = cbbd.models.shooting_line.ShootingLine(
                                    made = 1.337, 
                                    attempted = 1.337, 
                                    pct = 1.337, ), 
                                three_point_field_goals = , 
                                free_throws = , 
                                rebounds = cbbd.models.team_box_score_rebounds.TeamBoxScore_rebounds(
                                    total = 1.337, 
                                    defensive = 1.337, 
                                    offensive = 1.337, ), 
                                assists = 1.337, 
                                steals = 1.337, 
                                blocks = 1.337, 
                                turnovers = 1.337, 
                                fouls = 1.337, 
                                starts = 1.337, 
                                assist_turnover_ratio = 1.337, 
                                free_throw_rate = 1.337, 
                                offensive_rebound_pct = 1.337, 
                                advanced = cbbd.models.player_season_details_advanced.PlayerSeasonDetails_advanced(
                                    win_shares = cbbd.models.player_season_details_advanced_win_shares.PlayerSeasonDetails_advanced_winShares(
                                        per40 = 1.337, 
                                        total = 1.337, 
                                        defensive = 1.337, 
                                        offensive = 1.337, ), 
                                    porpag = 1.337, 
                                    net_rating = 1.337, 
                                    defensive_rating = 1.337, 
                                    offensive_rating = 1.337, 
                                    games = 1.337, ), ), 
                            athlete_id = 1.337, 
                            name = '', 
                            position = '', 
                            on_roster = True, 
                            has_stats = True, 
                            games = 1.337, 
                            minutes = 1.337, 
                            points = 1.337, 
                            rebounds = 1.337, 
                            assists = 1.337, 
                            minutes_per_game = 1.337, 
                            points_per_game = 1.337, 
                            usage_pct = 1.337, 
                            true_shooting_pct = 1.337, 
                            effective_field_goal_pct = 1.337, 
                            usage_games = 1.337, 
                            complete = True, )
                        ], 
                    coverage = cbbd.models.coverage.Coverage(
                        state = 'available', 
                        reason = null, 
                        eligible_games = 1.337, 
                        covered_games = 1.337, ), ),
                schedule = cbbd.models.team_season_overview_schedule.TeamSeasonOverview_schedule(
                    games = [
                        cbbd.models.profile_game.ProfileGame(
                            id = 1.337, 
                            opponent_id = 1.337, 
                            opponent = '', 
                            opponent_has_profile = True, 
                            start_date = '', 
                            calendar_date = '', 
                            start_time_tbd = True, 
                            location = 'home', 
                            status = 'scheduled', 
                            season_type = 'regular', 
                            game_type = '', 
                            eligibility = 'counted', 
                            conference_game = True, 
                            team_points = 1.337, 
                            opponent_points = 1.337, 
                            result = 'W', 
                            venue = '', )
                        ], ),
                sources = cbbd.models.team_season_overview_sources.TeamSeasonOverview_sources(
                    notes = [
                        ''
                        ], 
                    latest_final_start_date = '', 
                    leaderboard_updated_at = '', )
            )
        else:
            return TeamSeasonOverview(
                format_version = 1,
                team_id = 1.337,
                season = 1.337,
                season_label = '',
                generated_at = '',
                team = cbbd.models.team_season_overview_team.TeamSeasonOverview_team(
                    conference = cbbd.models.conference.Conference(
                        id = 1.337, 
                        name = '', 
                        abbreviation = '', ), 
                    source_id = '', 
                    mascot = '', 
                    school = '', ),
                record = cbbd.models.team_season_overview_record.TeamSeasonOverview_record(
                    unknown_conference_games = 1.337, 
                    unknown_eligibility_games = 1.337, 
                    complete = True, 
                    conference = cbbd.models.count_record.CountRecord(
                        games = 1.337, 
                        wins = 1.337, 
                        losses = 1.337, 
                        unresolved = 1.337, ), 
                    overall = cbbd.models.count_record.CountRecord(
                        games = 1.337, 
                        wins = 1.337, 
                        losses = 1.337, 
                        unresolved = 1.337, ), ),
                ratings = cbbd.models.team_season_overview_ratings.TeamSeasonOverview_ratings(
                    polls = cbbd.models.team_season_overview_ratings_polls.TeamSeasonOverview_ratings_polls(
                        coaches = cbbd.models.poll_standing.PollStanding(
                            state = 'ranked', 
                            date = '', 
                            week = 1.337, 
                            season_type = 'regular', 
                            rank = 1.337, ), 
                        ap = cbbd.models.poll_standing.PollStanding(
                            state = 'ranked', 
                            date = '', 
                            week = 1.337, 
                            season_type = 'regular', 
                            rank = 1.337, ), ), 
                    srs = 1.337, 
                    elo = 1.337, 
                    adjusted = null, ),
                efficiency = cbbd.models.team_season_overview_efficiency.TeamSeasonOverview_efficiency(
                    defense = cbbd.models.unit_metrics.UnitMetrics(
                        box_score = cbbd.models.team_box_score.TeamBoxScore(
                            field_goals = cbbd.models.shooting_line.ShootingLine(
                                made = 1.337, 
                                attempted = 1.337, 
                                pct = 1.337, ), 
                            two_point_field_goals = cbbd.models.shooting_line.ShootingLine(
                                made = 1.337, 
                                attempted = 1.337, 
                                pct = 1.337, ), 
                            three_point_field_goals = , 
                            free_throws = , 
                            rebounds = cbbd.models.team_box_score_rebounds.TeamBoxScore_rebounds(
                                total = 1.337, 
                                defensive = 1.337, 
                                offensive = 1.337, ), 
                            assists = 1.337, 
                            steals = 1.337, 
                            blocks = 1.337, 
                            turnovers = 1.337, 
                            fouls = 1.337, 
                            minutes = 1.337, 
                            team_turnovers = 1.337, 
                            technical_fouls = 1.337, 
                            flagrant_fouls = 1.337, 
                            points_in_paint = 1.337, 
                            points_off_turnovers = 1.337, 
                            fast_break_points = 1.337, 
                            true_shooting_pct = 1.337, ), 
                        points = 1.337, 
                        possessions = 1.337, 
                        raw_rating = 1.337, 
                        effective_field_goal_pct = 1.337, 
                        turnover_pct = 1.337, 
                        offensive_rebound_pct = 1.337, 
                        free_throw_rate = 1.337, ), 
                    offense = cbbd.models.unit_metrics.UnitMetrics(
                        points = 1.337, 
                        possessions = 1.337, 
                        raw_rating = 1.337, 
                        effective_field_goal_pct = 1.337, 
                        turnover_pct = 1.337, 
                        offensive_rebound_pct = 1.337, 
                        free_throw_rate = 1.337, ), 
                    pace_games = 1.337, 
                    pace = 1.337, 
                    coverage = cbbd.models.coverage.Coverage(
                        state = 'available', 
                        reason = null, 
                        eligible_games = 1.337, 
                        covered_games = 1.337, ), ),
                shooting = cbbd.models.team_season_overview_shooting.TeamSeasonOverview_shooting(
                    buckets = [
                        cbbd.models.shot_bucket.ShotBucket(
                            key = 'at_rim', 
                            attempts = 1.337, 
                            made = 1.337, 
                            attempt_pct = 1.337, 
                            field_goal_pct = 1.337, )
                        ], 
                    tracked_attempts = 1.337, 
                    coverage = cbbd.models.coverage.Coverage(
                        state = 'available', 
                        reason = null, 
                        eligible_games = 1.337, 
                        covered_games = 1.337, ), ),
                players = cbbd.models.team_season_overview_players.TeamSeasonOverview_players(
                    rows = [
                        cbbd.models.profile_player.ProfilePlayer(
                            season_stats = cbbd.models.player_season_details.PlayerSeasonDetails(
                                field_goals = cbbd.models.shooting_line.ShootingLine(
                                    made = 1.337, 
                                    attempted = 1.337, 
                                    pct = 1.337, ), 
                                two_point_field_goals = cbbd.models.shooting_line.ShootingLine(
                                    made = 1.337, 
                                    attempted = 1.337, 
                                    pct = 1.337, ), 
                                three_point_field_goals = , 
                                free_throws = , 
                                rebounds = cbbd.models.team_box_score_rebounds.TeamBoxScore_rebounds(
                                    total = 1.337, 
                                    defensive = 1.337, 
                                    offensive = 1.337, ), 
                                assists = 1.337, 
                                steals = 1.337, 
                                blocks = 1.337, 
                                turnovers = 1.337, 
                                fouls = 1.337, 
                                starts = 1.337, 
                                assist_turnover_ratio = 1.337, 
                                free_throw_rate = 1.337, 
                                offensive_rebound_pct = 1.337, 
                                advanced = cbbd.models.player_season_details_advanced.PlayerSeasonDetails_advanced(
                                    win_shares = cbbd.models.player_season_details_advanced_win_shares.PlayerSeasonDetails_advanced_winShares(
                                        per40 = 1.337, 
                                        total = 1.337, 
                                        defensive = 1.337, 
                                        offensive = 1.337, ), 
                                    porpag = 1.337, 
                                    net_rating = 1.337, 
                                    defensive_rating = 1.337, 
                                    offensive_rating = 1.337, 
                                    games = 1.337, ), ), 
                            athlete_id = 1.337, 
                            name = '', 
                            position = '', 
                            on_roster = True, 
                            has_stats = True, 
                            games = 1.337, 
                            minutes = 1.337, 
                            points = 1.337, 
                            rebounds = 1.337, 
                            assists = 1.337, 
                            minutes_per_game = 1.337, 
                            points_per_game = 1.337, 
                            usage_pct = 1.337, 
                            true_shooting_pct = 1.337, 
                            effective_field_goal_pct = 1.337, 
                            usage_games = 1.337, 
                            complete = True, )
                        ], 
                    coverage = cbbd.models.coverage.Coverage(
                        state = 'available', 
                        reason = null, 
                        eligible_games = 1.337, 
                        covered_games = 1.337, ), ),
                schedule = cbbd.models.team_season_overview_schedule.TeamSeasonOverview_schedule(
                    games = [
                        cbbd.models.profile_game.ProfileGame(
                            id = 1.337, 
                            opponent_id = 1.337, 
                            opponent = '', 
                            opponent_has_profile = True, 
                            start_date = '', 
                            calendar_date = '', 
                            start_time_tbd = True, 
                            location = 'home', 
                            status = 'scheduled', 
                            season_type = 'regular', 
                            game_type = '', 
                            eligibility = 'counted', 
                            conference_game = True, 
                            team_points = 1.337, 
                            opponent_points = 1.337, 
                            result = 'W', 
                            venue = '', )
                        ], ),
                sources = cbbd.models.team_season_overview_sources.TeamSeasonOverview_sources(
                    notes = [
                        ''
                        ], 
                    latest_final_start_date = '', 
                    leaderboard_updated_at = '', ),
        )
        """

    def testTeamSeasonOverview(self):
        """Test TeamSeasonOverview"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
