# coding: utf-8

"""
    College Basketball Data API

    Use the College Basketball Data API to query game, team, player, recruiting, and analytics data. Request an API key at [CollegeBasketballData.com](https://collegebasketballdata.com/key).

    The version of the OpenAPI document: 1.28.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cbbd.models.team_stats_leaderboard_shot_profile_free_throws import TeamStatsLeaderboardShotProfileFreeThrows  # noqa: E501

class TestTeamStatsLeaderboardShotProfileFreeThrows(unittest.TestCase):
    """TeamStatsLeaderboardShotProfileFreeThrows unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TeamStatsLeaderboardShotProfileFreeThrows:
        """Test TeamStatsLeaderboardShotProfileFreeThrows
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TeamStatsLeaderboardShotProfileFreeThrows`
        """
        model = TeamStatsLeaderboardShotProfileFreeThrows()  # noqa: E501
        if include_optional:
            return TeamStatsLeaderboardShotProfileFreeThrows(
                rate = 1.337,
                made = 1.337,
                attempts = 1.337
            )
        else:
            return TeamStatsLeaderboardShotProfileFreeThrows(
                rate = 1.337,
                made = 1.337,
                attempts = 1.337,
        )
        """

    def testTeamStatsLeaderboardShotProfileFreeThrows(self):
        """Test TeamStatsLeaderboardShotProfileFreeThrows"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
