# coding: utf-8

"""
    College Basketball Data API

    Use the College Basketball Data API to query game, team, player, recruiting, and analytics data. Request an API key at [CollegeBasketballData.com](https://collegebasketballdata.com/key).

    The version of the OpenAPI document: 1.30.1
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cbbd.models.profile_game import ProfileGame  # noqa: E501

class TestProfileGame(unittest.TestCase):
    """ProfileGame unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProfileGame:
        """Test ProfileGame
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProfileGame`
        """
        model = ProfileGame()  # noqa: E501
        if include_optional:
            return ProfileGame(
                id = 1.337,
                opponent_id = 1.337,
                opponent = '',
                opponent_has_profile = True,
                start_date = '',
                calendar_date = '',
                start_time_tbd = True,
                location = 'home',
                status = 'scheduled',
                season_type = 'regular',
                game_type = '',
                eligibility = 'counted',
                conference_game = True,
                team_points = 1.337,
                opponent_points = 1.337,
                result = 'W',
                venue = ''
            )
        else:
            return ProfileGame(
                id = 1.337,
                opponent_id = 1.337,
                opponent = '',
                opponent_has_profile = True,
                start_date = '',
                calendar_date = '',
                start_time_tbd = True,
                location = 'home',
                status = 'scheduled',
                season_type = 'regular',
                game_type = '',
                eligibility = 'counted',
                conference_game = True,
                team_points = 1.337,
                opponent_points = 1.337,
                result = 'W',
                venue = '',
        )
        """

    def testProfileGame(self):
        """Test ProfileGame"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
