# coding: utf-8

"""
    College Basketball Data API

    This is an API for query various college basketball datasets and analytics. API keys can be acquired by registering on the CollegeBasketballData.com website.

    The version of the OpenAPI document: 1.27.2
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cbbd.models.team_stats_leaderboard_shot_profile_dunk import TeamStatsLeaderboardShotProfileDunk  # noqa: E501

class TestTeamStatsLeaderboardShotProfileDunk(unittest.TestCase):
    """TeamStatsLeaderboardShotProfileDunk unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TeamStatsLeaderboardShotProfileDunk:
        """Test TeamStatsLeaderboardShotProfileDunk
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TeamStatsLeaderboardShotProfileDunk`
        """
        model = TeamStatsLeaderboardShotProfileDunk()  # noqa: E501
        if include_optional:
            return TeamStatsLeaderboardShotProfileDunk(
                rate = 1.337,
                assisted = 1.337,
                made = 1.337,
                attempts = 1.337
            )
        else:
            return TeamStatsLeaderboardShotProfileDunk(
                rate = 1.337,
                assisted = 1.337,
                made = 1.337,
                attempts = 1.337,
        )
        """

    def testTeamStatsLeaderboardShotProfileDunk(self):
        """Test TeamStatsLeaderboardShotProfileDunk"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
