# coding: utf-8

"""
    College Basketball Data API

    Use the College Basketball Data API to query game, team, player, recruiting, and analytics data. Request an API key at [CollegeBasketballData.com](https://collegebasketballdata.com/key).

    The version of the OpenAPI document: 1.29.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cbbd.models.team_season_overview_ratings_polls import TeamSeasonOverviewRatingsPolls  # noqa: E501

class TestTeamSeasonOverviewRatingsPolls(unittest.TestCase):
    """TeamSeasonOverviewRatingsPolls unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TeamSeasonOverviewRatingsPolls:
        """Test TeamSeasonOverviewRatingsPolls
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TeamSeasonOverviewRatingsPolls`
        """
        model = TeamSeasonOverviewRatingsPolls()  # noqa: E501
        if include_optional:
            return TeamSeasonOverviewRatingsPolls(
                coaches = cbbd.models.poll_standing.PollStanding(
                    state = 'ranked', 
                    date = '', 
                    week = 1.337, 
                    season_type = 'regular', 
                    rank = 1.337, ),
                ap = cbbd.models.poll_standing.PollStanding(
                    state = 'ranked', 
                    date = '', 
                    week = 1.337, 
                    season_type = 'regular', 
                    rank = 1.337, )
            )
        else:
            return TeamSeasonOverviewRatingsPolls(
                coaches = cbbd.models.poll_standing.PollStanding(
                    state = 'ranked', 
                    date = '', 
                    week = 1.337, 
                    season_type = 'regular', 
                    rank = 1.337, ),
                ap = cbbd.models.poll_standing.PollStanding(
                    state = 'ranked', 
                    date = '', 
                    week = 1.337, 
                    season_type = 'regular', 
                    rank = 1.337, ),
        )
        """

    def testTeamSeasonOverviewRatingsPolls(self):
        """Test TeamSeasonOverviewRatingsPolls"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
