# coding: utf-8

"""
    College Basketball Data API

    Use the College Basketball Data API to query game, team, player, recruiting, and analytics data. Request an API key at [CollegeBasketballData.com](https://collegebasketballdata.com/key).

    The version of the OpenAPI document: 1.30.1
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cbbd.models.team_season_overview_ratings import TeamSeasonOverviewRatings  # noqa: E501

class TestTeamSeasonOverviewRatings(unittest.TestCase):
    """TeamSeasonOverviewRatings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TeamSeasonOverviewRatings:
        """Test TeamSeasonOverviewRatings
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TeamSeasonOverviewRatings`
        """
        model = TeamSeasonOverviewRatings()  # noqa: E501
        if include_optional:
            return TeamSeasonOverviewRatings(
                polls = cbbd.models.team_season_overview_ratings_polls.TeamSeasonOverview_ratings_polls(
                    coaches = cbbd.models.poll_standing.PollStanding(
                        state = 'ranked', 
                        date = '', 
                        week = 1.337, 
                        season_type = 'regular', 
                        rank = 1.337, ), 
                    ap = cbbd.models.poll_standing.PollStanding(
                        state = 'ranked', 
                        date = '', 
                        week = 1.337, 
                        season_type = 'regular', 
                        rank = 1.337, ), ),
                srs = 1.337,
                elo = 1.337,
                adjusted = cbbd.models.adjusted_ratings.AdjustedRatings(
                    offense = cbbd.models.rated_value.RatedValue(
                        value = 1.337, 
                        rank = 1.337, ), 
                    defense = cbbd.models.rated_value.RatedValue(
                        value = 1.337, 
                        rank = 1.337, ), 
                    net = , 
                    population = 1.337, )
            )
        else:
            return TeamSeasonOverviewRatings(
                polls = cbbd.models.team_season_overview_ratings_polls.TeamSeasonOverview_ratings_polls(
                    coaches = cbbd.models.poll_standing.PollStanding(
                        state = 'ranked', 
                        date = '', 
                        week = 1.337, 
                        season_type = 'regular', 
                        rank = 1.337, ), 
                    ap = cbbd.models.poll_standing.PollStanding(
                        state = 'ranked', 
                        date = '', 
                        week = 1.337, 
                        season_type = 'regular', 
                        rank = 1.337, ), ),
                srs = 1.337,
                elo = 1.337,
                adjusted = cbbd.models.adjusted_ratings.AdjustedRatings(
                    offense = cbbd.models.rated_value.RatedValue(
                        value = 1.337, 
                        rank = 1.337, ), 
                    defense = cbbd.models.rated_value.RatedValue(
                        value = 1.337, 
                        rank = 1.337, ), 
                    net = , 
                    population = 1.337, ),
        )
        """

    def testTeamSeasonOverviewRatings(self):
        """Test TeamSeasonOverviewRatings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
