# coding: utf-8

"""
    College Basketball Data API

    Use the College Basketball Data API to query game, team, player, recruiting, and analytics data. Request an API key at [CollegeBasketballData.com](https://collegebasketballdata.com/key).

    The version of the OpenAPI document: 1.29.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cbbd.models.team_season_overview_players import TeamSeasonOverviewPlayers  # noqa: E501

class TestTeamSeasonOverviewPlayers(unittest.TestCase):
    """TeamSeasonOverviewPlayers unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TeamSeasonOverviewPlayers:
        """Test TeamSeasonOverviewPlayers
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TeamSeasonOverviewPlayers`
        """
        model = TeamSeasonOverviewPlayers()  # noqa: E501
        if include_optional:
            return TeamSeasonOverviewPlayers(
                rows = [
                    cbbd.models.profile_player.ProfilePlayer(
                        season_stats = cbbd.models.player_season_details.PlayerSeasonDetails(
                            field_goals = cbbd.models.shooting_line.ShootingLine(
                                made = 1.337, 
                                attempted = 1.337, 
                                pct = 1.337, ), 
                            two_point_field_goals = cbbd.models.shooting_line.ShootingLine(
                                made = 1.337, 
                                attempted = 1.337, 
                                pct = 1.337, ), 
                            three_point_field_goals = , 
                            free_throws = , 
                            rebounds = cbbd.models.team_box_score_rebounds.TeamBoxScore_rebounds(
                                total = 1.337, 
                                defensive = 1.337, 
                                offensive = 1.337, ), 
                            assists = 1.337, 
                            steals = 1.337, 
                            blocks = 1.337, 
                            turnovers = 1.337, 
                            fouls = 1.337, 
                            starts = 1.337, 
                            assist_turnover_ratio = 1.337, 
                            free_throw_rate = 1.337, 
                            offensive_rebound_pct = 1.337, 
                            advanced = cbbd.models.player_season_details_advanced.PlayerSeasonDetails_advanced(
                                win_shares = cbbd.models.player_season_details_advanced_win_shares.PlayerSeasonDetails_advanced_winShares(
                                    per40 = 1.337, 
                                    total = 1.337, 
                                    defensive = 1.337, 
                                    offensive = 1.337, ), 
                                porpag = 1.337, 
                                net_rating = 1.337, 
                                defensive_rating = 1.337, 
                                offensive_rating = 1.337, 
                                games = 1.337, ), ), 
                        athlete_id = 1.337, 
                        name = '', 
                        position = '', 
                        on_roster = True, 
                        has_stats = True, 
                        games = 1.337, 
                        minutes = 1.337, 
                        points = 1.337, 
                        rebounds = 1.337, 
                        assists = 1.337, 
                        minutes_per_game = 1.337, 
                        points_per_game = 1.337, 
                        usage_pct = 1.337, 
                        true_shooting_pct = 1.337, 
                        effective_field_goal_pct = 1.337, 
                        usage_games = 1.337, 
                        complete = True, )
                    ],
                coverage = cbbd.models.coverage.Coverage(
                    state = 'available', 
                    reason = null, 
                    eligible_games = 1.337, 
                    covered_games = 1.337, )
            )
        else:
            return TeamSeasonOverviewPlayers(
                rows = [
                    cbbd.models.profile_player.ProfilePlayer(
                        season_stats = cbbd.models.player_season_details.PlayerSeasonDetails(
                            field_goals = cbbd.models.shooting_line.ShootingLine(
                                made = 1.337, 
                                attempted = 1.337, 
                                pct = 1.337, ), 
                            two_point_field_goals = cbbd.models.shooting_line.ShootingLine(
                                made = 1.337, 
                                attempted = 1.337, 
                                pct = 1.337, ), 
                            three_point_field_goals = , 
                            free_throws = , 
                            rebounds = cbbd.models.team_box_score_rebounds.TeamBoxScore_rebounds(
                                total = 1.337, 
                                defensive = 1.337, 
                                offensive = 1.337, ), 
                            assists = 1.337, 
                            steals = 1.337, 
                            blocks = 1.337, 
                            turnovers = 1.337, 
                            fouls = 1.337, 
                            starts = 1.337, 
                            assist_turnover_ratio = 1.337, 
                            free_throw_rate = 1.337, 
                            offensive_rebound_pct = 1.337, 
                            advanced = cbbd.models.player_season_details_advanced.PlayerSeasonDetails_advanced(
                                win_shares = cbbd.models.player_season_details_advanced_win_shares.PlayerSeasonDetails_advanced_winShares(
                                    per40 = 1.337, 
                                    total = 1.337, 
                                    defensive = 1.337, 
                                    offensive = 1.337, ), 
                                porpag = 1.337, 
                                net_rating = 1.337, 
                                defensive_rating = 1.337, 
                                offensive_rating = 1.337, 
                                games = 1.337, ), ), 
                        athlete_id = 1.337, 
                        name = '', 
                        position = '', 
                        on_roster = True, 
                        has_stats = True, 
                        games = 1.337, 
                        minutes = 1.337, 
                        points = 1.337, 
                        rebounds = 1.337, 
                        assists = 1.337, 
                        minutes_per_game = 1.337, 
                        points_per_game = 1.337, 
                        usage_pct = 1.337, 
                        true_shooting_pct = 1.337, 
                        effective_field_goal_pct = 1.337, 
                        usage_games = 1.337, 
                        complete = True, )
                    ],
                coverage = cbbd.models.coverage.Coverage(
                    state = 'available', 
                    reason = null, 
                    eligible_games = 1.337, 
                    covered_games = 1.337, ),
        )
        """

    def testTeamSeasonOverviewPlayers(self):
        """Test TeamSeasonOverviewPlayers"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
