# coding: utf-8

"""
    College Basketball Data API

    Use the College Basketball Data API to query game, team, player, recruiting, and analytics data. Request an API key at [CollegeBasketballData.com](https://collegebasketballdata.com/key).

    The version of the OpenAPI document: 1.30.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cbbd.models.availability import Availability  # noqa: E501

class TestAvailability(unittest.TestCase):
    """Availability unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAvailability(self):
        """Test Availability"""
        # inst = Availability()

if __name__ == '__main__':
    unittest.main()
