# coding: utf-8

"""
    College Basketball Data API

    Use the College Basketball Data API to query game, team, player, recruiting, and analytics data. Request an API key at [CollegeBasketballData.com](https://collegebasketballdata.com/key).

    The version of the OpenAPI document: 1.30.1
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cbbd.models.unit_metrics import UnitMetrics  # noqa: E501

class TestUnitMetrics(unittest.TestCase):
    """UnitMetrics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UnitMetrics:
        """Test UnitMetrics
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UnitMetrics`
        """
        model = UnitMetrics()  # noqa: E501
        if include_optional:
            return UnitMetrics(
                box_score = cbbd.models.team_box_score.TeamBoxScore(
                    field_goals = cbbd.models.shooting_line.ShootingLine(
                        made = 1.337, 
                        attempted = 1.337, 
                        pct = 1.337, ), 
                    two_point_field_goals = cbbd.models.shooting_line.ShootingLine(
                        made = 1.337, 
                        attempted = 1.337, 
                        pct = 1.337, ), 
                    three_point_field_goals = , 
                    free_throws = , 
                    rebounds = cbbd.models.team_box_score_rebounds.TeamBoxScore_rebounds(
                        total = 1.337, 
                        defensive = 1.337, 
                        offensive = 1.337, ), 
                    assists = 1.337, 
                    steals = 1.337, 
                    blocks = 1.337, 
                    turnovers = 1.337, 
                    fouls = 1.337, 
                    minutes = 1.337, 
                    team_turnovers = 1.337, 
                    technical_fouls = 1.337, 
                    flagrant_fouls = 1.337, 
                    points_in_paint = 1.337, 
                    points_off_turnovers = 1.337, 
                    fast_break_points = 1.337, 
                    true_shooting_pct = 1.337, ),
                points = 1.337,
                possessions = 1.337,
                raw_rating = 1.337,
                effective_field_goal_pct = 1.337,
                turnover_pct = 1.337,
                offensive_rebound_pct = 1.337,
                free_throw_rate = 1.337
            )
        else:
            return UnitMetrics(
                points = 1.337,
                possessions = 1.337,
                raw_rating = 1.337,
                effective_field_goal_pct = 1.337,
                turnover_pct = 1.337,
                offensive_rebound_pct = 1.337,
                free_throw_rate = 1.337,
        )
        """

    def testUnitMetrics(self):
        """Test UnitMetrics"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
