# coding: utf-8

"""
    College Basketball Data API

    Use the College Basketball Data API to query game, team, player, recruiting, and analytics data. Request an API key at [CollegeBasketballData.com](https://collegebasketballdata.com/key).

    The version of the OpenAPI document: 1.28.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cbbd.models.scoreboard_game import ScoreboardGame  # noqa: E501

class TestScoreboardGame(unittest.TestCase):
    """ScoreboardGame unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScoreboardGame:
        """Test ScoreboardGame
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScoreboardGame`
        """
        model = ScoreboardGame()  # noqa: E501
        if include_optional:
            return ScoreboardGame(
                id = 56,
                start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                start_time_tbd = True,
                tv = '',
                neutral_site = True,
                conference_game = True,
                status = 'scheduled',
                period = 56,
                clock = '',
                venue = '',
                city = '',
                state = '',
                home_team = cbbd.models.scoreboard_game_home_team.ScoreboardGame_homeTeam(
                    line_scores = [
                        56
                        ], 
                    points = 56, 
                    conference_abbreviation = '', 
                    conference = '', 
                    location = '', 
                    name = '', 
                    id = 56, ),
                away_team = cbbd.models.scoreboard_game_home_team.ScoreboardGame_homeTeam(
                    line_scores = [
                        56
                        ], 
                    points = 56, 
                    conference_abbreviation = '', 
                    conference = '', 
                    location = '', 
                    name = '', 
                    id = 56, ),
                betting = cbbd.models.scoreboard_game_betting.ScoreboardGame_betting(
                    away_moneyline = 1.337, 
                    home_moneyline = 1.337, 
                    over_under = 1.337, 
                    spread = 1.337, )
            )
        else:
            return ScoreboardGame(
                id = 56,
                start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                start_time_tbd = True,
                tv = '',
                neutral_site = True,
                conference_game = True,
                status = 'scheduled',
                period = 56,
                clock = '',
                venue = '',
                city = '',
                state = '',
                home_team = cbbd.models.scoreboard_game_home_team.ScoreboardGame_homeTeam(
                    line_scores = [
                        56
                        ], 
                    points = 56, 
                    conference_abbreviation = '', 
                    conference = '', 
                    location = '', 
                    name = '', 
                    id = 56, ),
                away_team = cbbd.models.scoreboard_game_home_team.ScoreboardGame_homeTeam(
                    line_scores = [
                        56
                        ], 
                    points = 56, 
                    conference_abbreviation = '', 
                    conference = '', 
                    location = '', 
                    name = '', 
                    id = 56, ),
                betting = cbbd.models.scoreboard_game_betting.ScoreboardGame_betting(
                    away_moneyline = 1.337, 
                    home_moneyline = 1.337, 
                    over_under = 1.337, 
                    spread = 1.337, ),
        )
        """

    def testScoreboardGame(self):
        """Test ScoreboardGame"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
