# coding: utf-8

"""
    College Basketball Data API

    This is an API for query various college basketball datasets and analytics. API keys can be acquired by registering on the CollegeBasketballData.com website.

    The version of the OpenAPI document: 1.27.2
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cbbd.models.transfer_eligibility import TransferEligibility  # noqa: E501

class TestTransferEligibility(unittest.TestCase):
    """TransferEligibility unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransferEligibility(self):
        """Test TransferEligibility"""
        # inst = TransferEligibility()

if __name__ == '__main__':
    unittest.main()
