# coding: utf-8

"""
    College Basketball Data API

    This is an API for query various college basketball datasets and analytics. API keys can be acquired by registering on the CollegeBasketballData.com website.

    The version of the OpenAPI document: 1.27.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cbbd.models.transfer import Transfer  # noqa: E501

class TestTransfer(unittest.TestCase):
    """Transfer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Transfer:
        """Test Transfer
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Transfer`
        """
        model = Transfer()  # noqa: E501
        if include_optional:
            return Transfer(
                id = 56,
                source_id = '',
                year = 56,
                first_name = '',
                last_name = '',
                position = '',
                origin = cbbd.models.transfer_origin.Transfer_origin(
                    conference = '', 
                    name = '', 
                    id = 56, ),
                destination = cbbd.models.recruit_committed_to.Recruit_committedTo(
                    conference = '', 
                    name = '', 
                    id = 56, ),
                eligibility = 'Withdrawn',
                years_remaining = 56,
                stars = 56,
                rating = 1.337
            )
        else:
            return Transfer(
                id = 56,
                source_id = '',
                year = 56,
                first_name = '',
                last_name = '',
                position = '',
                origin = cbbd.models.transfer_origin.Transfer_origin(
                    conference = '', 
                    name = '', 
                    id = 56, ),
                destination = cbbd.models.recruit_committed_to.Recruit_committedTo(
                    conference = '', 
                    name = '', 
                    id = 56, ),
                eligibility = 'Withdrawn',
                years_remaining = 56,
                stars = 56,
                rating = 1.337,
        )
        """

    def testTransfer(self):
        """Test Transfer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
