# coding: utf-8

"""
    College Basketball Data API

    Use the College Basketball Data API to query game, team, player, recruiting, and analytics data. Request an API key at [CollegeBasketballData.com](https://collegebasketballdata.com/key).

    The version of the OpenAPI document: 1.28.1
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cbbd.models.game_status import GameStatus  # noqa: E501

class TestGameStatus(unittest.TestCase):
    """GameStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGameStatus(self):
        """Test GameStatus"""
        # inst = GameStatus()

if __name__ == '__main__':
    unittest.main()
