# coding: utf-8

"""
    College Basketball Data API

    Use the College Basketball Data API to query game, team, player, recruiting, and analytics data. Request an API key at [CollegeBasketballData.com](https://collegebasketballdata.com/key).

    The version of the OpenAPI document: 1.30.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cbbd.models.team_season_overview_shooting import TeamSeasonOverviewShooting  # noqa: E501

class TestTeamSeasonOverviewShooting(unittest.TestCase):
    """TeamSeasonOverviewShooting unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TeamSeasonOverviewShooting:
        """Test TeamSeasonOverviewShooting
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TeamSeasonOverviewShooting`
        """
        model = TeamSeasonOverviewShooting()  # noqa: E501
        if include_optional:
            return TeamSeasonOverviewShooting(
                buckets = [
                    cbbd.models.shot_bucket.ShotBucket(
                        key = 'at_rim', 
                        attempts = 1.337, 
                        made = 1.337, 
                        attempt_pct = 1.337, 
                        field_goal_pct = 1.337, )
                    ],
                tracked_attempts = 1.337,
                coverage = cbbd.models.coverage.Coverage(
                    state = 'available', 
                    reason = null, 
                    eligible_games = 1.337, 
                    covered_games = 1.337, )
            )
        else:
            return TeamSeasonOverviewShooting(
                buckets = [
                    cbbd.models.shot_bucket.ShotBucket(
                        key = 'at_rim', 
                        attempts = 1.337, 
                        made = 1.337, 
                        attempt_pct = 1.337, 
                        field_goal_pct = 1.337, )
                    ],
                tracked_attempts = 1.337,
                coverage = cbbd.models.coverage.Coverage(
                    state = 'available', 
                    reason = null, 
                    eligible_games = 1.337, 
                    covered_games = 1.337, ),
        )
        """

    def testTeamSeasonOverviewShooting(self):
        """Test TeamSeasonOverviewShooting"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
