# coding: utf-8

"""
    College Basketball Data API

    Use the College Basketball Data API to query game, team, player, recruiting, and analytics data. Request an API key at [CollegeBasketballData.com](https://collegebasketballdata.com/key).

    The version of the OpenAPI document: 1.30.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class Availability(str, Enum):
    """
    Availability
    """

    """
    allowed enum values
    """
    AVAILABLE = 'available'
    PARTIAL = 'partial'
    UNAVAILABLE = 'unavailable'

    @classmethod
    def from_json(cls, json_str: str) -> Availability:
        """Create an instance of Availability from a JSON string"""
        return Availability(json.loads(json_str))


