# coding: utf-8

"""
    College Basketball Data API

    Use the College Basketball Data API to query game, team, player, recruiting, and analytics data. Request an API key at [CollegeBasketballData.com](https://collegebasketballdata.com/key).

    The version of the OpenAPI document: 1.30.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt
from cbbd.models.availability import Availability
from cbbd.models.reason import Reason

class Coverage(BaseModel):
    """
    Coverage
    """
    state: Availability = Field(...)
    reason: Optional[Reason] = Field(...)
    eligible_games: Union[StrictFloat, StrictInt] = Field(default=..., alias="eligibleGames")
    covered_games: Union[StrictFloat, StrictInt] = Field(default=..., alias="coveredGames")
    __properties = ["state", "reason", "eligibleGames", "coveredGames"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Coverage:
        """Create an instance of Coverage from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if reason (nullable) is None
        # and __fields_set__ contains the field
        if self.reason is None and "reason" in self.__fields_set__:
            _dict['reason'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Coverage:
        """Create an instance of Coverage from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Coverage.parse_obj(obj)

        _obj = Coverage.parse_obj({
            "state": obj.get("state"),
            "reason": obj.get("reason"),
            "eligible_games": obj.get("eligibleGames"),
            "covered_games": obj.get("coveredGames")
        })
        return _obj


