# coding: utf-8

"""
    College Basketball Data API

    Use the College Basketball Data API to query game, team, player, recruiting, and analytics data. Request an API key at [CollegeBasketballData.com](https://collegebasketballdata.com/key).

    The version of the OpenAPI document: 1.30.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt, StrictStr

class DirectoryTeam(BaseModel):
    """
    DirectoryTeam
    """
    id: Union[StrictFloat, StrictInt] = Field(...)
    source_id: Optional[StrictStr] = Field(default=..., alias="sourceId")
    school: StrictStr = Field(...)
    mascot: Optional[StrictStr] = Field(...)
    abbreviation: Optional[StrictStr] = Field(...)
    display_name: Optional[StrictStr] = Field(default=..., alias="displayName")
    short_display_name: Optional[StrictStr] = Field(default=..., alias="shortDisplayName")
    conference_id: Union[StrictFloat, StrictInt] = Field(default=..., alias="conferenceId")
    __properties = ["id", "sourceId", "school", "mascot", "abbreviation", "displayName", "shortDisplayName", "conferenceId"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DirectoryTeam:
        """Create an instance of DirectoryTeam from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if source_id (nullable) is None
        # and __fields_set__ contains the field
        if self.source_id is None and "source_id" in self.__fields_set__:
            _dict['sourceId'] = None

        # set to None if mascot (nullable) is None
        # and __fields_set__ contains the field
        if self.mascot is None and "mascot" in self.__fields_set__:
            _dict['mascot'] = None

        # set to None if abbreviation (nullable) is None
        # and __fields_set__ contains the field
        if self.abbreviation is None and "abbreviation" in self.__fields_set__:
            _dict['abbreviation'] = None

        # set to None if display_name (nullable) is None
        # and __fields_set__ contains the field
        if self.display_name is None and "display_name" in self.__fields_set__:
            _dict['displayName'] = None

        # set to None if short_display_name (nullable) is None
        # and __fields_set__ contains the field
        if self.short_display_name is None and "short_display_name" in self.__fields_set__:
            _dict['shortDisplayName'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DirectoryTeam:
        """Create an instance of DirectoryTeam from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return DirectoryTeam.parse_obj(obj)

        _obj = DirectoryTeam.parse_obj({
            "id": obj.get("id"),
            "source_id": obj.get("sourceId"),
            "school": obj.get("school"),
            "mascot": obj.get("mascot"),
            "abbreviation": obj.get("abbreviation"),
            "display_name": obj.get("displayName"),
            "short_display_name": obj.get("shortDisplayName"),
            "conference_id": obj.get("conferenceId")
        })
        return _obj


