# coding: utf-8

"""
    College Basketball Data API

    Use the College Basketball Data API to query game, team, player, recruiting, and analytics data. Request an API key at [CollegeBasketballData.com](https://collegebasketballdata.com/key).

    The version of the OpenAPI document: 1.30.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt
from cbbd.models.player_season_details_advanced_win_shares import PlayerSeasonDetailsAdvancedWinShares

class PlayerSeasonDetailsAdvanced(BaseModel):
    """
    PlayerSeasonDetailsAdvanced
    """
    win_shares: PlayerSeasonDetailsAdvancedWinShares = Field(default=..., alias="winShares")
    porpag: Optional[Union[StrictFloat, StrictInt]] = Field(...)
    net_rating: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="netRating")
    defensive_rating: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="defensiveRating")
    offensive_rating: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="offensiveRating")
    games: Union[StrictFloat, StrictInt] = Field(...)
    __properties = ["winShares", "porpag", "netRating", "defensiveRating", "offensiveRating", "games"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PlayerSeasonDetailsAdvanced:
        """Create an instance of PlayerSeasonDetailsAdvanced from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of win_shares
        if self.win_shares:
            _dict['winShares'] = self.win_shares.to_dict()
        # set to None if porpag (nullable) is None
        # and __fields_set__ contains the field
        if self.porpag is None and "porpag" in self.__fields_set__:
            _dict['porpag'] = None

        # set to None if net_rating (nullable) is None
        # and __fields_set__ contains the field
        if self.net_rating is None and "net_rating" in self.__fields_set__:
            _dict['netRating'] = None

        # set to None if defensive_rating (nullable) is None
        # and __fields_set__ contains the field
        if self.defensive_rating is None and "defensive_rating" in self.__fields_set__:
            _dict['defensiveRating'] = None

        # set to None if offensive_rating (nullable) is None
        # and __fields_set__ contains the field
        if self.offensive_rating is None and "offensive_rating" in self.__fields_set__:
            _dict['offensiveRating'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PlayerSeasonDetailsAdvanced:
        """Create an instance of PlayerSeasonDetailsAdvanced from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PlayerSeasonDetailsAdvanced.parse_obj(obj)

        _obj = PlayerSeasonDetailsAdvanced.parse_obj({
            "win_shares": PlayerSeasonDetailsAdvancedWinShares.from_dict(obj.get("winShares")) if obj.get("winShares") is not None else None,
            "porpag": obj.get("porpag"),
            "net_rating": obj.get("netRating"),
            "defensive_rating": obj.get("defensiveRating"),
            "offensive_rating": obj.get("offensiveRating"),
            "games": obj.get("games")
        })
        return _obj


