# coding: utf-8

"""
    College Basketball Data API

    Use the College Basketball Data API to query game, team, player, recruiting, and analytics data. Request an API key at [CollegeBasketballData.com](https://collegebasketballdata.com/key).

    The version of the OpenAPI document: 1.29.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt
from cbbd.models.player_season_details_advanced import PlayerSeasonDetailsAdvanced
from cbbd.models.shooting_line import ShootingLine
from cbbd.models.team_box_score_rebounds import TeamBoxScoreRebounds

class PlayerSeasonDetails(BaseModel):
    """
    PlayerSeasonDetails
    """
    field_goals: ShootingLine = Field(default=..., alias="fieldGoals")
    two_point_field_goals: ShootingLine = Field(default=..., alias="twoPointFieldGoals")
    three_point_field_goals: ShootingLine = Field(default=..., alias="threePointFieldGoals")
    free_throws: ShootingLine = Field(default=..., alias="freeThrows")
    rebounds: TeamBoxScoreRebounds = Field(...)
    assists: Optional[Union[StrictFloat, StrictInt]] = Field(...)
    steals: Optional[Union[StrictFloat, StrictInt]] = Field(...)
    blocks: Optional[Union[StrictFloat, StrictInt]] = Field(...)
    turnovers: Optional[Union[StrictFloat, StrictInt]] = Field(...)
    fouls: Optional[Union[StrictFloat, StrictInt]] = Field(...)
    starts: Optional[Union[StrictFloat, StrictInt]] = Field(...)
    assist_turnover_ratio: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="assistTurnoverRatio")
    free_throw_rate: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="freeThrowRate")
    offensive_rebound_pct: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="offensiveReboundPct")
    advanced: PlayerSeasonDetailsAdvanced = Field(...)
    __properties = ["fieldGoals", "twoPointFieldGoals", "threePointFieldGoals", "freeThrows", "rebounds", "assists", "steals", "blocks", "turnovers", "fouls", "starts", "assistTurnoverRatio", "freeThrowRate", "offensiveReboundPct", "advanced"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PlayerSeasonDetails:
        """Create an instance of PlayerSeasonDetails from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of field_goals
        if self.field_goals:
            _dict['fieldGoals'] = self.field_goals.to_dict()
        # override the default output from pydantic by calling `to_dict()` of two_point_field_goals
        if self.two_point_field_goals:
            _dict['twoPointFieldGoals'] = self.two_point_field_goals.to_dict()
        # override the default output from pydantic by calling `to_dict()` of three_point_field_goals
        if self.three_point_field_goals:
            _dict['threePointFieldGoals'] = self.three_point_field_goals.to_dict()
        # override the default output from pydantic by calling `to_dict()` of free_throws
        if self.free_throws:
            _dict['freeThrows'] = self.free_throws.to_dict()
        # override the default output from pydantic by calling `to_dict()` of rebounds
        if self.rebounds:
            _dict['rebounds'] = self.rebounds.to_dict()
        # override the default output from pydantic by calling `to_dict()` of advanced
        if self.advanced:
            _dict['advanced'] = self.advanced.to_dict()
        # set to None if assists (nullable) is None
        # and __fields_set__ contains the field
        if self.assists is None and "assists" in self.__fields_set__:
            _dict['assists'] = None

        # set to None if steals (nullable) is None
        # and __fields_set__ contains the field
        if self.steals is None and "steals" in self.__fields_set__:
            _dict['steals'] = None

        # set to None if blocks (nullable) is None
        # and __fields_set__ contains the field
        if self.blocks is None and "blocks" in self.__fields_set__:
            _dict['blocks'] = None

        # set to None if turnovers (nullable) is None
        # and __fields_set__ contains the field
        if self.turnovers is None and "turnovers" in self.__fields_set__:
            _dict['turnovers'] = None

        # set to None if fouls (nullable) is None
        # and __fields_set__ contains the field
        if self.fouls is None and "fouls" in self.__fields_set__:
            _dict['fouls'] = None

        # set to None if starts (nullable) is None
        # and __fields_set__ contains the field
        if self.starts is None and "starts" in self.__fields_set__:
            _dict['starts'] = None

        # set to None if assist_turnover_ratio (nullable) is None
        # and __fields_set__ contains the field
        if self.assist_turnover_ratio is None and "assist_turnover_ratio" in self.__fields_set__:
            _dict['assistTurnoverRatio'] = None

        # set to None if free_throw_rate (nullable) is None
        # and __fields_set__ contains the field
        if self.free_throw_rate is None and "free_throw_rate" in self.__fields_set__:
            _dict['freeThrowRate'] = None

        # set to None if offensive_rebound_pct (nullable) is None
        # and __fields_set__ contains the field
        if self.offensive_rebound_pct is None and "offensive_rebound_pct" in self.__fields_set__:
            _dict['offensiveReboundPct'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PlayerSeasonDetails:
        """Create an instance of PlayerSeasonDetails from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PlayerSeasonDetails.parse_obj(obj)

        _obj = PlayerSeasonDetails.parse_obj({
            "field_goals": ShootingLine.from_dict(obj.get("fieldGoals")) if obj.get("fieldGoals") is not None else None,
            "two_point_field_goals": ShootingLine.from_dict(obj.get("twoPointFieldGoals")) if obj.get("twoPointFieldGoals") is not None else None,
            "three_point_field_goals": ShootingLine.from_dict(obj.get("threePointFieldGoals")) if obj.get("threePointFieldGoals") is not None else None,
            "free_throws": ShootingLine.from_dict(obj.get("freeThrows")) if obj.get("freeThrows") is not None else None,
            "rebounds": TeamBoxScoreRebounds.from_dict(obj.get("rebounds")) if obj.get("rebounds") is not None else None,
            "assists": obj.get("assists"),
            "steals": obj.get("steals"),
            "blocks": obj.get("blocks"),
            "turnovers": obj.get("turnovers"),
            "fouls": obj.get("fouls"),
            "starts": obj.get("starts"),
            "assist_turnover_ratio": obj.get("assistTurnoverRatio"),
            "free_throw_rate": obj.get("freeThrowRate"),
            "offensive_rebound_pct": obj.get("offensiveReboundPct"),
            "advanced": PlayerSeasonDetailsAdvanced.from_dict(obj.get("advanced")) if obj.get("advanced") is not None else None
        })
        return _obj


