# coding: utf-8

"""
    College Basketball Data API

    Use the College Basketball Data API to query game, team, player, recruiting, and analytics data. Request an API key at [CollegeBasketballData.com](https://collegebasketballdata.com/key).

    The version of the OpenAPI document: 1.30.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt, StrictStr, validator

class PollStanding(BaseModel):
    """
    PollStanding
    """
    state: StrictStr = Field(...)
    var_date: Optional[StrictStr] = Field(default=..., alias="date")
    week: Optional[Union[StrictFloat, StrictInt]] = Field(...)
    season_type: Optional[StrictStr] = Field(default=..., alias="seasonType")
    rank: Optional[Union[StrictFloat, StrictInt]] = Field(...)
    __properties = ["state", "date", "week", "seasonType", "rank"]

    @validator('state')
    def state_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('ranked', 'unranked', 'unavailable',):
            raise ValueError("must be one of enum values ('ranked', 'unranked', 'unavailable')")
        return value

    @validator('season_type')
    def season_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('regular', 'postseason', 'preseason',):
            raise ValueError("must be one of enum values ('regular', 'postseason', 'preseason')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PollStanding:
        """Create an instance of PollStanding from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if var_date (nullable) is None
        # and __fields_set__ contains the field
        if self.var_date is None and "var_date" in self.__fields_set__:
            _dict['date'] = None

        # set to None if week (nullable) is None
        # and __fields_set__ contains the field
        if self.week is None and "week" in self.__fields_set__:
            _dict['week'] = None

        # set to None if season_type (nullable) is None
        # and __fields_set__ contains the field
        if self.season_type is None and "season_type" in self.__fields_set__:
            _dict['seasonType'] = None

        # set to None if rank (nullable) is None
        # and __fields_set__ contains the field
        if self.rank is None and "rank" in self.__fields_set__:
            _dict['rank'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PollStanding:
        """Create an instance of PollStanding from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PollStanding.parse_obj(obj)

        _obj = PollStanding.parse_obj({
            "state": obj.get("state"),
            "var_date": obj.get("date"),
            "week": obj.get("week"),
            "season_type": obj.get("seasonType"),
            "rank": obj.get("rank")
        })
        return _obj


