# coding: utf-8

"""
    College Basketball Data API

    Use the College Basketball Data API to query game, team, player, recruiting, and analytics data. Request an API key at [CollegeBasketballData.com](https://collegebasketballdata.com/key).

    The version of the OpenAPI document: 1.30.1
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional, Union
from pydantic import BaseModel, Field, StrictBool, StrictFloat, StrictInt, StrictStr, validator

class ProfileGame(BaseModel):
    """
    ProfileGame
    """
    id: Union[StrictFloat, StrictInt] = Field(...)
    opponent_id: Union[StrictFloat, StrictInt] = Field(default=..., alias="opponentId")
    opponent: StrictStr = Field(...)
    opponent_has_profile: StrictBool = Field(default=..., alias="opponentHasProfile")
    start_date: StrictStr = Field(default=..., alias="startDate")
    calendar_date: StrictStr = Field(default=..., alias="calendarDate")
    start_time_tbd: StrictBool = Field(default=..., alias="startTimeTbd")
    location: StrictStr = Field(...)
    status: StrictStr = Field(...)
    season_type: StrictStr = Field(default=..., alias="seasonType")
    game_type: Optional[StrictStr] = Field(default=..., alias="gameType")
    eligibility: StrictStr = Field(...)
    conference_game: Optional[StrictBool] = Field(default=..., alias="conferenceGame")
    team_points: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="teamPoints")
    opponent_points: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="opponentPoints")
    result: Optional[StrictStr] = Field(...)
    venue: Optional[StrictStr] = Field(...)
    __properties = ["id", "opponentId", "opponent", "opponentHasProfile", "startDate", "calendarDate", "startTimeTbd", "location", "status", "seasonType", "gameType", "eligibility", "conferenceGame", "teamPoints", "opponentPoints", "result", "venue"]

    @validator('location')
    def location_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('home', 'away', 'neutral',):
            raise ValueError("must be one of enum values ('home', 'away', 'neutral')")
        return value

    @validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('scheduled', 'in_progress', 'final', 'postponed', 'cancelled',):
            raise ValueError("must be one of enum values ('scheduled', 'in_progress', 'final', 'postponed', 'cancelled')")
        return value

    @validator('season_type')
    def season_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('regular', 'postseason', 'preseason',):
            raise ValueError("must be one of enum values ('regular', 'postseason', 'preseason')")
        return value

    @validator('eligibility')
    def eligibility_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('counted', 'exhibition', 'unknown',):
            raise ValueError("must be one of enum values ('counted', 'exhibition', 'unknown')")
        return value

    @validator('result')
    def result_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('W', 'L',):
            raise ValueError("must be one of enum values ('W', 'L')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ProfileGame:
        """Create an instance of ProfileGame from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if game_type (nullable) is None
        # and __fields_set__ contains the field
        if self.game_type is None and "game_type" in self.__fields_set__:
            _dict['gameType'] = None

        # set to None if conference_game (nullable) is None
        # and __fields_set__ contains the field
        if self.conference_game is None and "conference_game" in self.__fields_set__:
            _dict['conferenceGame'] = None

        # set to None if team_points (nullable) is None
        # and __fields_set__ contains the field
        if self.team_points is None and "team_points" in self.__fields_set__:
            _dict['teamPoints'] = None

        # set to None if opponent_points (nullable) is None
        # and __fields_set__ contains the field
        if self.opponent_points is None and "opponent_points" in self.__fields_set__:
            _dict['opponentPoints'] = None

        # set to None if result (nullable) is None
        # and __fields_set__ contains the field
        if self.result is None and "result" in self.__fields_set__:
            _dict['result'] = None

        # set to None if venue (nullable) is None
        # and __fields_set__ contains the field
        if self.venue is None and "venue" in self.__fields_set__:
            _dict['venue'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ProfileGame:
        """Create an instance of ProfileGame from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ProfileGame.parse_obj(obj)

        _obj = ProfileGame.parse_obj({
            "id": obj.get("id"),
            "opponent_id": obj.get("opponentId"),
            "opponent": obj.get("opponent"),
            "opponent_has_profile": obj.get("opponentHasProfile"),
            "start_date": obj.get("startDate"),
            "calendar_date": obj.get("calendarDate"),
            "start_time_tbd": obj.get("startTimeTbd"),
            "location": obj.get("location"),
            "status": obj.get("status"),
            "season_type": obj.get("seasonType"),
            "game_type": obj.get("gameType"),
            "eligibility": obj.get("eligibility"),
            "conference_game": obj.get("conferenceGame"),
            "team_points": obj.get("teamPoints"),
            "opponent_points": obj.get("opponentPoints"),
            "result": obj.get("result"),
            "venue": obj.get("venue")
        })
        return _obj


