# coding: utf-8

"""
    College Basketball Data API

    Use the College Basketball Data API to query game, team, player, recruiting, and analytics data. Request an API key at [CollegeBasketballData.com](https://collegebasketballdata.com/key).

    The version of the OpenAPI document: 1.30.1
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional, Union
from pydantic import BaseModel, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from cbbd.models.player_season_details import PlayerSeasonDetails

class ProfilePlayer(BaseModel):
    """
    ProfilePlayer
    """
    season_stats: Optional[PlayerSeasonDetails] = Field(default=None, alias="seasonStats")
    athlete_id: Union[StrictFloat, StrictInt] = Field(default=..., alias="athleteId")
    name: StrictStr = Field(...)
    position: Optional[StrictStr] = Field(...)
    on_roster: StrictBool = Field(default=..., alias="onRoster")
    has_stats: StrictBool = Field(default=..., alias="hasStats")
    games: Optional[Union[StrictFloat, StrictInt]] = Field(...)
    minutes: Optional[Union[StrictFloat, StrictInt]] = Field(...)
    points: Optional[Union[StrictFloat, StrictInt]] = Field(...)
    rebounds: Optional[Union[StrictFloat, StrictInt]] = Field(...)
    assists: Optional[Union[StrictFloat, StrictInt]] = Field(...)
    minutes_per_game: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="minutesPerGame")
    points_per_game: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="pointsPerGame")
    usage_pct: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="usagePct")
    true_shooting_pct: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="trueShootingPct")
    effective_field_goal_pct: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="effectiveFieldGoalPct")
    usage_games: Union[StrictFloat, StrictInt] = Field(default=..., alias="usageGames")
    complete: StrictBool = Field(...)
    __properties = ["seasonStats", "athleteId", "name", "position", "onRoster", "hasStats", "games", "minutes", "points", "rebounds", "assists", "minutesPerGame", "pointsPerGame", "usagePct", "trueShootingPct", "effectiveFieldGoalPct", "usageGames", "complete"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ProfilePlayer:
        """Create an instance of ProfilePlayer from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of season_stats
        if self.season_stats:
            _dict['seasonStats'] = self.season_stats.to_dict()
        # set to None if position (nullable) is None
        # and __fields_set__ contains the field
        if self.position is None and "position" in self.__fields_set__:
            _dict['position'] = None

        # set to None if games (nullable) is None
        # and __fields_set__ contains the field
        if self.games is None and "games" in self.__fields_set__:
            _dict['games'] = None

        # set to None if minutes (nullable) is None
        # and __fields_set__ contains the field
        if self.minutes is None and "minutes" in self.__fields_set__:
            _dict['minutes'] = None

        # set to None if points (nullable) is None
        # and __fields_set__ contains the field
        if self.points is None and "points" in self.__fields_set__:
            _dict['points'] = None

        # set to None if rebounds (nullable) is None
        # and __fields_set__ contains the field
        if self.rebounds is None and "rebounds" in self.__fields_set__:
            _dict['rebounds'] = None

        # set to None if assists (nullable) is None
        # and __fields_set__ contains the field
        if self.assists is None and "assists" in self.__fields_set__:
            _dict['assists'] = None

        # set to None if minutes_per_game (nullable) is None
        # and __fields_set__ contains the field
        if self.minutes_per_game is None and "minutes_per_game" in self.__fields_set__:
            _dict['minutesPerGame'] = None

        # set to None if points_per_game (nullable) is None
        # and __fields_set__ contains the field
        if self.points_per_game is None and "points_per_game" in self.__fields_set__:
            _dict['pointsPerGame'] = None

        # set to None if usage_pct (nullable) is None
        # and __fields_set__ contains the field
        if self.usage_pct is None and "usage_pct" in self.__fields_set__:
            _dict['usagePct'] = None

        # set to None if true_shooting_pct (nullable) is None
        # and __fields_set__ contains the field
        if self.true_shooting_pct is None and "true_shooting_pct" in self.__fields_set__:
            _dict['trueShootingPct'] = None

        # set to None if effective_field_goal_pct (nullable) is None
        # and __fields_set__ contains the field
        if self.effective_field_goal_pct is None and "effective_field_goal_pct" in self.__fields_set__:
            _dict['effectiveFieldGoalPct'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ProfilePlayer:
        """Create an instance of ProfilePlayer from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ProfilePlayer.parse_obj(obj)

        _obj = ProfilePlayer.parse_obj({
            "season_stats": PlayerSeasonDetails.from_dict(obj.get("seasonStats")) if obj.get("seasonStats") is not None else None,
            "athlete_id": obj.get("athleteId"),
            "name": obj.get("name"),
            "position": obj.get("position"),
            "on_roster": obj.get("onRoster"),
            "has_stats": obj.get("hasStats"),
            "games": obj.get("games"),
            "minutes": obj.get("minutes"),
            "points": obj.get("points"),
            "rebounds": obj.get("rebounds"),
            "assists": obj.get("assists"),
            "minutes_per_game": obj.get("minutesPerGame"),
            "points_per_game": obj.get("pointsPerGame"),
            "usage_pct": obj.get("usagePct"),
            "true_shooting_pct": obj.get("trueShootingPct"),
            "effective_field_goal_pct": obj.get("effectiveFieldGoalPct"),
            "usage_games": obj.get("usageGames"),
            "complete": obj.get("complete")
        })
        return _obj


