# coding: utf-8

"""
    College Basketball Data API

    Use the College Basketball Data API to query game, team, player, recruiting, and analytics data. Request an API key at [CollegeBasketballData.com](https://collegebasketballdata.com/key).

    The version of the OpenAPI document: 1.30.1
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class Reason(str, Enum):
    """
    Reason
    """

    """
    allowed enum values
    """
    NO_GAMES = 'no_games'
    NO_SOURCE_ROWS = 'no_source_rows'
    INCOMPLETE_INPUTS = 'incomplete_inputs'
    ZERO_DENOMINATOR = 'zero_denominator'
    UNCLASSIFIED_GAMES = 'unclassified_games'
    UNCLASSIFIED_SHOTS = 'unclassified_shots'

    @classmethod
    def from_json(cls, json_str: str) -> Reason:
        """Create an instance of Reason from a JSON string"""
        return Reason(json.loads(json_str))


