# coding: utf-8

"""
    College Basketball Data API

    Use the College Basketball Data API to query game, team, player, recruiting, and analytics data. Request an API key at [CollegeBasketballData.com](https://collegebasketballdata.com/key).

    The version of the OpenAPI document: 1.29.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt

class ShootingLine(BaseModel):
    """
    ShootingLine
    """
    made: Optional[Union[StrictFloat, StrictInt]] = Field(...)
    attempted: Optional[Union[StrictFloat, StrictInt]] = Field(...)
    pct: Optional[Union[StrictFloat, StrictInt]] = Field(...)
    __properties = ["made", "attempted", "pct"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ShootingLine:
        """Create an instance of ShootingLine from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if made (nullable) is None
        # and __fields_set__ contains the field
        if self.made is None and "made" in self.__fields_set__:
            _dict['made'] = None

        # set to None if attempted (nullable) is None
        # and __fields_set__ contains the field
        if self.attempted is None and "attempted" in self.__fields_set__:
            _dict['attempted'] = None

        # set to None if pct (nullable) is None
        # and __fields_set__ contains the field
        if self.pct is None and "pct" in self.__fields_set__:
            _dict['pct'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ShootingLine:
        """Create an instance of ShootingLine from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ShootingLine.parse_obj(obj)

        _obj = ShootingLine.parse_obj({
            "made": obj.get("made"),
            "attempted": obj.get("attempted"),
            "pct": obj.get("pct")
        })
        return _obj


