# coding: utf-8

"""
    College Basketball Data API

    Use the College Basketball Data API to query game, team, player, recruiting, and analytics data. Request an API key at [CollegeBasketballData.com](https://collegebasketballdata.com/key).

    The version of the OpenAPI document: 1.30.1
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt, StrictStr, validator

class ShotBucket(BaseModel):
    """
    ShotBucket
    """
    key: StrictStr = Field(...)
    attempts: Union[StrictFloat, StrictInt] = Field(...)
    made: Union[StrictFloat, StrictInt] = Field(...)
    attempt_pct: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="attemptPct")
    field_goal_pct: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="fieldGoalPct")
    __properties = ["key", "attempts", "made", "attemptPct", "fieldGoalPct"]

    @validator('key')
    def key_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('at_rim', 'two_point_jumper', 'three_point_jumper', 'unknown',):
            raise ValueError("must be one of enum values ('at_rim', 'two_point_jumper', 'three_point_jumper', 'unknown')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ShotBucket:
        """Create an instance of ShotBucket from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if attempt_pct (nullable) is None
        # and __fields_set__ contains the field
        if self.attempt_pct is None and "attempt_pct" in self.__fields_set__:
            _dict['attemptPct'] = None

        # set to None if field_goal_pct (nullable) is None
        # and __fields_set__ contains the field
        if self.field_goal_pct is None and "field_goal_pct" in self.__fields_set__:
            _dict['fieldGoalPct'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ShotBucket:
        """Create an instance of ShotBucket from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ShotBucket.parse_obj(obj)

        _obj = ShotBucket.parse_obj({
            "key": obj.get("key"),
            "attempts": obj.get("attempts"),
            "made": obj.get("made"),
            "attempt_pct": obj.get("attemptPct"),
            "field_goal_pct": obj.get("fieldGoalPct")
        })
        return _obj


