# coding: utf-8

"""
    College Basketball Data API

    Use the College Basketball Data API to query game, team, player, recruiting, and analytics data. Request an API key at [CollegeBasketballData.com](https://collegebasketballdata.com/key).

    The version of the OpenAPI document: 1.30.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Union
from pydantic import BaseModel, Field, StrictBool, StrictFloat, StrictInt
from cbbd.models.count_record import CountRecord

class TeamSeasonOverviewRecord(BaseModel):
    """
    TeamSeasonOverviewRecord
    """
    unknown_conference_games: Union[StrictFloat, StrictInt] = Field(default=..., alias="unknownConferenceGames")
    unknown_eligibility_games: Union[StrictFloat, StrictInt] = Field(default=..., alias="unknownEligibilityGames")
    complete: StrictBool = Field(...)
    conference: CountRecord = Field(...)
    overall: CountRecord = Field(...)
    __properties = ["unknownConferenceGames", "unknownEligibilityGames", "complete", "conference", "overall"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TeamSeasonOverviewRecord:
        """Create an instance of TeamSeasonOverviewRecord from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of conference
        if self.conference:
            _dict['conference'] = self.conference.to_dict()
        # override the default output from pydantic by calling `to_dict()` of overall
        if self.overall:
            _dict['overall'] = self.overall.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TeamSeasonOverviewRecord:
        """Create an instance of TeamSeasonOverviewRecord from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TeamSeasonOverviewRecord.parse_obj(obj)

        _obj = TeamSeasonOverviewRecord.parse_obj({
            "unknown_conference_games": obj.get("unknownConferenceGames"),
            "unknown_eligibility_games": obj.get("unknownEligibilityGames"),
            "complete": obj.get("complete"),
            "conference": CountRecord.from_dict(obj.get("conference")) if obj.get("conference") is not None else None,
            "overall": CountRecord.from_dict(obj.get("overall")) if obj.get("overall") is not None else None
        })
        return _obj


