# coding: utf-8

"""
    College Basketball Data API

    Use the College Basketball Data API to query game, team, player, recruiting, and analytics data. Request an API key at [CollegeBasketballData.com](https://collegebasketballdata.com/key).

    The version of the OpenAPI document: 1.30.1
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt
from cbbd.models.adjusted_ratings import AdjustedRatings
from cbbd.models.team_season_overview_ratings_polls import TeamSeasonOverviewRatingsPolls

class TeamSeasonOverviewRatings(BaseModel):
    """
    TeamSeasonOverviewRatings
    """
    polls: TeamSeasonOverviewRatingsPolls = Field(...)
    srs: Optional[Union[StrictFloat, StrictInt]] = Field(...)
    elo: Optional[Union[StrictFloat, StrictInt]] = Field(...)
    adjusted: Optional[AdjustedRatings] = Field(...)
    __properties = ["polls", "srs", "elo", "adjusted"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TeamSeasonOverviewRatings:
        """Create an instance of TeamSeasonOverviewRatings from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of polls
        if self.polls:
            _dict['polls'] = self.polls.to_dict()
        # override the default output from pydantic by calling `to_dict()` of adjusted
        if self.adjusted:
            _dict['adjusted'] = self.adjusted.to_dict()
        # set to None if srs (nullable) is None
        # and __fields_set__ contains the field
        if self.srs is None and "srs" in self.__fields_set__:
            _dict['srs'] = None

        # set to None if elo (nullable) is None
        # and __fields_set__ contains the field
        if self.elo is None and "elo" in self.__fields_set__:
            _dict['elo'] = None

        # set to None if adjusted (nullable) is None
        # and __fields_set__ contains the field
        if self.adjusted is None and "adjusted" in self.__fields_set__:
            _dict['adjusted'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TeamSeasonOverviewRatings:
        """Create an instance of TeamSeasonOverviewRatings from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TeamSeasonOverviewRatings.parse_obj(obj)

        _obj = TeamSeasonOverviewRatings.parse_obj({
            "polls": TeamSeasonOverviewRatingsPolls.from_dict(obj.get("polls")) if obj.get("polls") is not None else None,
            "srs": obj.get("srs"),
            "elo": obj.get("elo"),
            "adjusted": AdjustedRatings.from_dict(obj.get("adjusted")) if obj.get("adjusted") is not None else None
        })
        return _obj


