# coding: utf-8

"""
    College Basketball Data API

    Use the College Basketball Data API to query game, team, player, recruiting, and analytics data. Request an API key at [CollegeBasketballData.com](https://collegebasketballdata.com/key).

    The version of the OpenAPI document: 1.30.1
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt, StrictStr, conlist
from cbbd.models.conference import Conference
from cbbd.models.directory_team import DirectoryTeam

class TeamDirectory(BaseModel):
    """
    TeamDirectory
    """
    season: Union[StrictFloat, StrictInt] = Field(...)
    season_label: StrictStr = Field(default=..., alias="seasonLabel")
    teams: conlist(DirectoryTeam) = Field(...)
    conferences: conlist(Conference) = Field(...)
    __properties = ["season", "seasonLabel", "teams", "conferences"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TeamDirectory:
        """Create an instance of TeamDirectory from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in teams (list)
        _items = []
        if self.teams:
            for _item in self.teams:
                if _item:
                    _items.append(_item.to_dict())
            _dict['teams'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in conferences (list)
        _items = []
        if self.conferences:
            for _item in self.conferences:
                if _item:
                    _items.append(_item.to_dict())
            _dict['conferences'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TeamDirectory:
        """Create an instance of TeamDirectory from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TeamDirectory.parse_obj(obj)

        _obj = TeamDirectory.parse_obj({
            "season": obj.get("season"),
            "season_label": obj.get("seasonLabel"),
            "teams": [DirectoryTeam.from_dict(_item) for _item in obj.get("teams")] if obj.get("teams") is not None else None,
            "conferences": [Conference.from_dict(_item) for _item in obj.get("conferences")] if obj.get("conferences") is not None else None
        })
        return _obj


