# coding: utf-8

"""
    College Basketball Data API

    This is an API for query various college basketball datasets and analytics. API keys can be acquired by registering on the CollegeBasketballData.com website.

    The version of the OpenAPI document: 1.27.1
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt

class TeamStatsLeaderboardShotProfileDistribution(BaseModel):
    """
    TeamStatsLeaderboardShotProfileDistribution
    """
    three_rate: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="threeRate")
    jumper_rate: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="jumperRate")
    midrange_rate: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="midrangeRate")
    __properties = ["threeRate", "jumperRate", "midrangeRate"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TeamStatsLeaderboardShotProfileDistribution:
        """Create an instance of TeamStatsLeaderboardShotProfileDistribution from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if three_rate (nullable) is None
        # and __fields_set__ contains the field
        if self.three_rate is None and "three_rate" in self.__fields_set__:
            _dict['threeRate'] = None

        # set to None if jumper_rate (nullable) is None
        # and __fields_set__ contains the field
        if self.jumper_rate is None and "jumper_rate" in self.__fields_set__:
            _dict['jumperRate'] = None

        # set to None if midrange_rate (nullable) is None
        # and __fields_set__ contains the field
        if self.midrange_rate is None and "midrange_rate" in self.__fields_set__:
            _dict['midrangeRate'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TeamStatsLeaderboardShotProfileDistribution:
        """Create an instance of TeamStatsLeaderboardShotProfileDistribution from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TeamStatsLeaderboardShotProfileDistribution.parse_obj(obj)

        _obj = TeamStatsLeaderboardShotProfileDistribution.parse_obj({
            "three_rate": obj.get("threeRate"),
            "jumper_rate": obj.get("jumperRate"),
            "midrange_rate": obj.get("midrangeRate")
        })
        return _obj


