# coding: utf-8

"""
    College Basketball Data API

    This is an API for query various college basketball datasets and analytics. API keys can be acquired by registering on the CollegeBasketballData.com website.

    The version of the OpenAPI document: 1.26.3
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt

class TeamLeaderboardAdjustedEfficiencyRankings(BaseModel):
    """
    TeamLeaderboardAdjustedEfficiencyRankings
    """
    net: Optional[Union[StrictFloat, StrictInt]] = Field(...)
    defense: Optional[Union[StrictFloat, StrictInt]] = Field(...)
    offense: Optional[Union[StrictFloat, StrictInt]] = Field(...)
    __properties = ["net", "defense", "offense"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TeamLeaderboardAdjustedEfficiencyRankings:
        """Create an instance of TeamLeaderboardAdjustedEfficiencyRankings from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if net (nullable) is None
        # and __fields_set__ contains the field
        if self.net is None and "net" in self.__fields_set__:
            _dict['net'] = None

        # set to None if defense (nullable) is None
        # and __fields_set__ contains the field
        if self.defense is None and "defense" in self.__fields_set__:
            _dict['defense'] = None

        # set to None if offense (nullable) is None
        # and __fields_set__ contains the field
        if self.offense is None and "offense" in self.__fields_set__:
            _dict['offense'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TeamLeaderboardAdjustedEfficiencyRankings:
        """Create an instance of TeamLeaderboardAdjustedEfficiencyRankings from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TeamLeaderboardAdjustedEfficiencyRankings.parse_obj(obj)

        _obj = TeamLeaderboardAdjustedEfficiencyRankings.parse_obj({
            "net": obj.get("net"),
            "defense": obj.get("defense"),
            "offense": obj.get("offense")
        })
        return _obj


