# coding: utf-8

"""
    College Basketball Data API

    This is an API for query various college basketball datasets and analytics. API keys can be acquired by registering on the CollegeBasketballData.com website.

    The version of the OpenAPI document: 1.26.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt
from cbbd.models.team_stats_leaderboard_shot_profile_at_rim import TeamStatsLeaderboardShotProfileAtRim
from cbbd.models.team_stats_leaderboard_shot_profile_distribution import TeamStatsLeaderboardShotProfileDistribution
from cbbd.models.team_stats_leaderboard_shot_profile_dunk import TeamStatsLeaderboardShotProfileDunk
from cbbd.models.team_stats_leaderboard_shot_profile_free_throws import TeamStatsLeaderboardShotProfileFreeThrows
from cbbd.models.team_stats_leaderboard_shot_profile_tip_in import TeamStatsLeaderboardShotProfileTipIn
from cbbd.models.team_stats_leaderboard_shot_profile_two_point_jumper import TeamStatsLeaderboardShotProfileTwoPointJumper

class TeamStatsLeaderboardShotProfile(BaseModel):
    """
    TeamStatsLeaderboardShotProfile
    """
    assisted_pct: Union[StrictFloat, StrictInt] = Field(default=..., alias="assistedPct")
    at_rim: TeamStatsLeaderboardShotProfileAtRim = Field(default=..., alias="atRim")
    dunk: TeamStatsLeaderboardShotProfileDunk = Field(...)
    layup: TeamStatsLeaderboardShotProfileDunk = Field(...)
    tip_in: TeamStatsLeaderboardShotProfileTipIn = Field(default=..., alias="tipIn")
    two_point_jumper: TeamStatsLeaderboardShotProfileTwoPointJumper = Field(default=..., alias="twoPointJumper")
    three_point_jumper: TeamStatsLeaderboardShotProfileTwoPointJumper = Field(default=..., alias="threePointJumper")
    free_throws: TeamStatsLeaderboardShotProfileFreeThrows = Field(default=..., alias="freeThrows")
    distribution: TeamStatsLeaderboardShotProfileDistribution = Field(...)
    __properties = ["assistedPct", "atRim", "dunk", "layup", "tipIn", "twoPointJumper", "threePointJumper", "freeThrows", "distribution"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TeamStatsLeaderboardShotProfile:
        """Create an instance of TeamStatsLeaderboardShotProfile from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of at_rim
        if self.at_rim:
            _dict['atRim'] = self.at_rim.to_dict()
        # override the default output from pydantic by calling `to_dict()` of dunk
        if self.dunk:
            _dict['dunk'] = self.dunk.to_dict()
        # override the default output from pydantic by calling `to_dict()` of layup
        if self.layup:
            _dict['layup'] = self.layup.to_dict()
        # override the default output from pydantic by calling `to_dict()` of tip_in
        if self.tip_in:
            _dict['tipIn'] = self.tip_in.to_dict()
        # override the default output from pydantic by calling `to_dict()` of two_point_jumper
        if self.two_point_jumper:
            _dict['twoPointJumper'] = self.two_point_jumper.to_dict()
        # override the default output from pydantic by calling `to_dict()` of three_point_jumper
        if self.three_point_jumper:
            _dict['threePointJumper'] = self.three_point_jumper.to_dict()
        # override the default output from pydantic by calling `to_dict()` of free_throws
        if self.free_throws:
            _dict['freeThrows'] = self.free_throws.to_dict()
        # override the default output from pydantic by calling `to_dict()` of distribution
        if self.distribution:
            _dict['distribution'] = self.distribution.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TeamStatsLeaderboardShotProfile:
        """Create an instance of TeamStatsLeaderboardShotProfile from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TeamStatsLeaderboardShotProfile.parse_obj(obj)

        _obj = TeamStatsLeaderboardShotProfile.parse_obj({
            "assisted_pct": obj.get("assistedPct"),
            "at_rim": TeamStatsLeaderboardShotProfileAtRim.from_dict(obj.get("atRim")) if obj.get("atRim") is not None else None,
            "dunk": TeamStatsLeaderboardShotProfileDunk.from_dict(obj.get("dunk")) if obj.get("dunk") is not None else None,
            "layup": TeamStatsLeaderboardShotProfileDunk.from_dict(obj.get("layup")) if obj.get("layup") is not None else None,
            "tip_in": TeamStatsLeaderboardShotProfileTipIn.from_dict(obj.get("tipIn")) if obj.get("tipIn") is not None else None,
            "two_point_jumper": TeamStatsLeaderboardShotProfileTwoPointJumper.from_dict(obj.get("twoPointJumper")) if obj.get("twoPointJumper") is not None else None,
            "three_point_jumper": TeamStatsLeaderboardShotProfileTwoPointJumper.from_dict(obj.get("threePointJumper")) if obj.get("threePointJumper") is not None else None,
            "free_throws": TeamStatsLeaderboardShotProfileFreeThrows.from_dict(obj.get("freeThrows")) if obj.get("freeThrows") is not None else None,
            "distribution": TeamStatsLeaderboardShotProfileDistribution.from_dict(obj.get("distribution")) if obj.get("distribution") is not None else None
        })
        return _obj


