# coding: utf-8

"""
    College Basketball Data API

    Use the College Basketball Data API to query game, team, player, recruiting, and analytics data. Request an API key at [CollegeBasketballData.com](https://collegebasketballdata.com/key).

    The version of the OpenAPI document: 1.29.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictStr, conlist

class TeamSeasonOverviewSources(BaseModel):
    """
    TeamSeasonOverviewSources
    """
    notes: conlist(StrictStr) = Field(...)
    latest_final_start_date: Optional[StrictStr] = Field(default=..., alias="latestFinalStartDate")
    leaderboard_updated_at: Optional[StrictStr] = Field(default=..., alias="leaderboardUpdatedAt")
    __properties = ["notes", "latestFinalStartDate", "leaderboardUpdatedAt"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TeamSeasonOverviewSources:
        """Create an instance of TeamSeasonOverviewSources from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if latest_final_start_date (nullable) is None
        # and __fields_set__ contains the field
        if self.latest_final_start_date is None and "latest_final_start_date" in self.__fields_set__:
            _dict['latestFinalStartDate'] = None

        # set to None if leaderboard_updated_at (nullable) is None
        # and __fields_set__ contains the field
        if self.leaderboard_updated_at is None and "leaderboard_updated_at" in self.__fields_set__:
            _dict['leaderboardUpdatedAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TeamSeasonOverviewSources:
        """Create an instance of TeamSeasonOverviewSources from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TeamSeasonOverviewSources.parse_obj(obj)

        _obj = TeamSeasonOverviewSources.parse_obj({
            "notes": obj.get("notes"),
            "latest_final_start_date": obj.get("latestFinalStartDate"),
            "leaderboard_updated_at": obj.get("leaderboardUpdatedAt")
        })
        return _obj


