# coding: utf-8

"""
    College Basketball Data API

    Use the College Basketball Data API to query game, team, player, recruiting, and analytics data. Request an API key at [CollegeBasketballData.com](https://collegebasketballdata.com/key).

    The version of the OpenAPI document: 1.30.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field
from cbbd.models.poll_standing import PollStanding

class TeamSeasonOverviewRatingsPolls(BaseModel):
    """
    TeamSeasonOverviewRatingsPolls
    """
    coaches: PollStanding = Field(...)
    ap: PollStanding = Field(...)
    __properties = ["coaches", "ap"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TeamSeasonOverviewRatingsPolls:
        """Create an instance of TeamSeasonOverviewRatingsPolls from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of coaches
        if self.coaches:
            _dict['coaches'] = self.coaches.to_dict()
        # override the default output from pydantic by calling `to_dict()` of ap
        if self.ap:
            _dict['ap'] = self.ap.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TeamSeasonOverviewRatingsPolls:
        """Create an instance of TeamSeasonOverviewRatingsPolls from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TeamSeasonOverviewRatingsPolls.parse_obj(obj)

        _obj = TeamSeasonOverviewRatingsPolls.parse_obj({
            "coaches": PollStanding.from_dict(obj.get("coaches")) if obj.get("coaches") is not None else None,
            "ap": PollStanding.from_dict(obj.get("ap")) if obj.get("ap") is not None else None
        })
        return _obj


