# coding: utf-8

"""
    College Basketball Data API

    This is an API for query various college basketball datasets and analytics. API keys can be acquired by registering on the CollegeBasketballData.com website.

    The version of the OpenAPI document: 1.27.3
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt

class TeamStatsLeaderboardSummary(BaseModel):
    """
    TeamStatsLeaderboardSummary
    """
    total_minutes: Union[StrictFloat, StrictInt] = Field(default=..., alias="totalMinutes")
    tracked_shots: Union[StrictFloat, StrictInt] = Field(default=..., alias="trackedShots")
    pace: Optional[Union[StrictFloat, StrictInt]] = Field(...)
    raw_net_rating: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="rawNetRating")
    __properties = ["totalMinutes", "trackedShots", "pace", "rawNetRating"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TeamStatsLeaderboardSummary:
        """Create an instance of TeamStatsLeaderboardSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if pace (nullable) is None
        # and __fields_set__ contains the field
        if self.pace is None and "pace" in self.__fields_set__:
            _dict['pace'] = None

        # set to None if raw_net_rating (nullable) is None
        # and __fields_set__ contains the field
        if self.raw_net_rating is None and "raw_net_rating" in self.__fields_set__:
            _dict['rawNetRating'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TeamStatsLeaderboardSummary:
        """Create an instance of TeamStatsLeaderboardSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TeamStatsLeaderboardSummary.parse_obj(obj)

        _obj = TeamStatsLeaderboardSummary.parse_obj({
            "total_minutes": obj.get("totalMinutes"),
            "tracked_shots": obj.get("trackedShots"),
            "pace": obj.get("pace"),
            "raw_net_rating": obj.get("rawNetRating")
        })
        return _obj


