# coding: utf-8

"""
    College Basketball Data API

    This is an API for query various college basketball datasets and analytics. API keys can be acquired by registering on the CollegeBasketballData.com website.

    The version of the OpenAPI document: 1.26.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt

class TeamStatsLeaderboardShotProfileAtRim(BaseModel):
    """
    TeamStatsLeaderboardShotProfileAtRim
    """
    assisted_pct: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="assistedPct")
    pct: Optional[Union[StrictFloat, StrictInt]] = Field(...)
    rate: Optional[Union[StrictFloat, StrictInt]] = Field(...)
    __properties = ["assistedPct", "pct", "rate"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TeamStatsLeaderboardShotProfileAtRim:
        """Create an instance of TeamStatsLeaderboardShotProfileAtRim from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if assisted_pct (nullable) is None
        # and __fields_set__ contains the field
        if self.assisted_pct is None and "assisted_pct" in self.__fields_set__:
            _dict['assistedPct'] = None

        # set to None if pct (nullable) is None
        # and __fields_set__ contains the field
        if self.pct is None and "pct" in self.__fields_set__:
            _dict['pct'] = None

        # set to None if rate (nullable) is None
        # and __fields_set__ contains the field
        if self.rate is None and "rate" in self.__fields_set__:
            _dict['rate'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TeamStatsLeaderboardShotProfileAtRim:
        """Create an instance of TeamStatsLeaderboardShotProfileAtRim from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TeamStatsLeaderboardShotProfileAtRim.parse_obj(obj)

        _obj = TeamStatsLeaderboardShotProfileAtRim.parse_obj({
            "assisted_pct": obj.get("assistedPct"),
            "pct": obj.get("pct"),
            "rate": obj.get("rate")
        })
        return _obj


