# coding: utf-8

"""
    College Basketball Data API

    This is an API for query various college basketball datasets and analytics. API keys can be acquired by registering on the CollegeBasketballData.com website.

    The version of the OpenAPI document: 1.27.2
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr
from cbbd.models.team_leaderboard_adjusted_efficiency import TeamLeaderboardAdjustedEfficiency
from cbbd.models.team_stats_leaderboard_conference import TeamStatsLeaderboardConference
from cbbd.models.team_stats_leaderboard_record_summary import TeamStatsLeaderboardRecordSummary
from cbbd.models.team_stats_leaderboard_shot_profile import TeamStatsLeaderboardShotProfile
from cbbd.models.team_stats_leaderboard_summary import TeamStatsLeaderboardSummary
from cbbd.models.team_stats_leaderboard_unit_stats import TeamStatsLeaderboardUnitStats

class TeamStatsLeaderboardRecord(BaseModel):
    """
    TeamStatsLeaderboardRecord
    """
    season: StrictInt = Field(...)
    team_id: StrictInt = Field(default=..., alias="teamId")
    team: StrictStr = Field(...)
    conference: TeamStatsLeaderboardConference = Field(...)
    record: TeamStatsLeaderboardRecordSummary = Field(...)
    summary: TeamStatsLeaderboardSummary = Field(...)
    team_stats: TeamStatsLeaderboardUnitStats = Field(default=..., alias="teamStats")
    opponent_stats: TeamStatsLeaderboardUnitStats = Field(default=..., alias="opponentStats")
    shot_profile: TeamStatsLeaderboardShotProfile = Field(default=..., alias="shotProfile")
    adjusted_efficiency: Optional[TeamLeaderboardAdjustedEfficiency] = Field(default=..., alias="adjustedEfficiency")
    __properties = ["season", "teamId", "team", "conference", "record", "summary", "teamStats", "opponentStats", "shotProfile", "adjustedEfficiency"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TeamStatsLeaderboardRecord:
        """Create an instance of TeamStatsLeaderboardRecord from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of conference
        if self.conference:
            _dict['conference'] = self.conference.to_dict()
        # override the default output from pydantic by calling `to_dict()` of record
        if self.record:
            _dict['record'] = self.record.to_dict()
        # override the default output from pydantic by calling `to_dict()` of summary
        if self.summary:
            _dict['summary'] = self.summary.to_dict()
        # override the default output from pydantic by calling `to_dict()` of team_stats
        if self.team_stats:
            _dict['teamStats'] = self.team_stats.to_dict()
        # override the default output from pydantic by calling `to_dict()` of opponent_stats
        if self.opponent_stats:
            _dict['opponentStats'] = self.opponent_stats.to_dict()
        # override the default output from pydantic by calling `to_dict()` of shot_profile
        if self.shot_profile:
            _dict['shotProfile'] = self.shot_profile.to_dict()
        # override the default output from pydantic by calling `to_dict()` of adjusted_efficiency
        if self.adjusted_efficiency:
            _dict['adjustedEfficiency'] = self.adjusted_efficiency.to_dict()
        # set to None if adjusted_efficiency (nullable) is None
        # and __fields_set__ contains the field
        if self.adjusted_efficiency is None and "adjusted_efficiency" in self.__fields_set__:
            _dict['adjustedEfficiency'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TeamStatsLeaderboardRecord:
        """Create an instance of TeamStatsLeaderboardRecord from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TeamStatsLeaderboardRecord.parse_obj(obj)

        _obj = TeamStatsLeaderboardRecord.parse_obj({
            "season": obj.get("season"),
            "team_id": obj.get("teamId"),
            "team": obj.get("team"),
            "conference": TeamStatsLeaderboardConference.from_dict(obj.get("conference")) if obj.get("conference") is not None else None,
            "record": TeamStatsLeaderboardRecordSummary.from_dict(obj.get("record")) if obj.get("record") is not None else None,
            "summary": TeamStatsLeaderboardSummary.from_dict(obj.get("summary")) if obj.get("summary") is not None else None,
            "team_stats": TeamStatsLeaderboardUnitStats.from_dict(obj.get("teamStats")) if obj.get("teamStats") is not None else None,
            "opponent_stats": TeamStatsLeaderboardUnitStats.from_dict(obj.get("opponentStats")) if obj.get("opponentStats") is not None else None,
            "shot_profile": TeamStatsLeaderboardShotProfile.from_dict(obj.get("shotProfile")) if obj.get("shotProfile") is not None else None,
            "adjusted_efficiency": TeamLeaderboardAdjustedEfficiency.from_dict(obj.get("adjustedEfficiency")) if obj.get("adjustedEfficiency") is not None else None
        })
        return _obj


