# coding: utf-8

"""
    College Basketball Data API

    This is an API for query various college basketball datasets and analytics. API keys can be acquired by registering on the CollegeBasketballData.com website.

    The version of the OpenAPI document: 1.26.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt
from cbbd.models.team_stats_leaderboard_unit_stats_field_goals import TeamStatsLeaderboardUnitStatsFieldGoals
from cbbd.models.team_stats_leaderboard_unit_stats_fouls import TeamStatsLeaderboardUnitStatsFouls
from cbbd.models.team_stats_leaderboard_unit_stats_points import TeamStatsLeaderboardUnitStatsPoints
from cbbd.models.team_stats_leaderboard_unit_stats_rebounds import TeamStatsLeaderboardUnitStatsRebounds
from cbbd.models.team_stats_leaderboard_unit_stats_turnovers import TeamStatsLeaderboardUnitStatsTurnovers

class TeamStatsLeaderboardUnitStats(BaseModel):
    """
    TeamStatsLeaderboardUnitStats
    """
    points: TeamStatsLeaderboardUnitStatsPoints = Field(...)
    possessions: Union[StrictFloat, StrictInt] = Field(...)
    raw_offensive_rating: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="rawOffensiveRating")
    true_shooting_pct: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="trueShootingPct")
    effective_field_goal_pct: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="effectiveFieldGoalPct")
    turnover_ratio: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="turnoverRatio")
    offensive_rebound_pct: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="offensiveReboundPct")
    free_throw_rate: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="freeThrowRate")
    field_goals: TeamStatsLeaderboardUnitStatsFieldGoals = Field(default=..., alias="fieldGoals")
    two_point_field_goals: TeamStatsLeaderboardUnitStatsFieldGoals = Field(default=..., alias="twoPointFieldGoals")
    three_point_field_goals: TeamStatsLeaderboardUnitStatsFieldGoals = Field(default=..., alias="threePointFieldGoals")
    free_throws: TeamStatsLeaderboardUnitStatsFieldGoals = Field(default=..., alias="freeThrows")
    rebounds: TeamStatsLeaderboardUnitStatsRebounds = Field(...)
    turnovers: TeamStatsLeaderboardUnitStatsTurnovers = Field(...)
    fouls: TeamStatsLeaderboardUnitStatsFouls = Field(...)
    assists: Union[StrictFloat, StrictInt] = Field(...)
    blocks: Union[StrictFloat, StrictInt] = Field(...)
    steals: Union[StrictFloat, StrictInt] = Field(...)
    __properties = ["points", "possessions", "rawOffensiveRating", "trueShootingPct", "effectiveFieldGoalPct", "turnoverRatio", "offensiveReboundPct", "freeThrowRate", "fieldGoals", "twoPointFieldGoals", "threePointFieldGoals", "freeThrows", "rebounds", "turnovers", "fouls", "assists", "blocks", "steals"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TeamStatsLeaderboardUnitStats:
        """Create an instance of TeamStatsLeaderboardUnitStats from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of points
        if self.points:
            _dict['points'] = self.points.to_dict()
        # override the default output from pydantic by calling `to_dict()` of field_goals
        if self.field_goals:
            _dict['fieldGoals'] = self.field_goals.to_dict()
        # override the default output from pydantic by calling `to_dict()` of two_point_field_goals
        if self.two_point_field_goals:
            _dict['twoPointFieldGoals'] = self.two_point_field_goals.to_dict()
        # override the default output from pydantic by calling `to_dict()` of three_point_field_goals
        if self.three_point_field_goals:
            _dict['threePointFieldGoals'] = self.three_point_field_goals.to_dict()
        # override the default output from pydantic by calling `to_dict()` of free_throws
        if self.free_throws:
            _dict['freeThrows'] = self.free_throws.to_dict()
        # override the default output from pydantic by calling `to_dict()` of rebounds
        if self.rebounds:
            _dict['rebounds'] = self.rebounds.to_dict()
        # override the default output from pydantic by calling `to_dict()` of turnovers
        if self.turnovers:
            _dict['turnovers'] = self.turnovers.to_dict()
        # override the default output from pydantic by calling `to_dict()` of fouls
        if self.fouls:
            _dict['fouls'] = self.fouls.to_dict()
        # set to None if raw_offensive_rating (nullable) is None
        # and __fields_set__ contains the field
        if self.raw_offensive_rating is None and "raw_offensive_rating" in self.__fields_set__:
            _dict['rawOffensiveRating'] = None

        # set to None if true_shooting_pct (nullable) is None
        # and __fields_set__ contains the field
        if self.true_shooting_pct is None and "true_shooting_pct" in self.__fields_set__:
            _dict['trueShootingPct'] = None

        # set to None if effective_field_goal_pct (nullable) is None
        # and __fields_set__ contains the field
        if self.effective_field_goal_pct is None and "effective_field_goal_pct" in self.__fields_set__:
            _dict['effectiveFieldGoalPct'] = None

        # set to None if turnover_ratio (nullable) is None
        # and __fields_set__ contains the field
        if self.turnover_ratio is None and "turnover_ratio" in self.__fields_set__:
            _dict['turnoverRatio'] = None

        # set to None if offensive_rebound_pct (nullable) is None
        # and __fields_set__ contains the field
        if self.offensive_rebound_pct is None and "offensive_rebound_pct" in self.__fields_set__:
            _dict['offensiveReboundPct'] = None

        # set to None if free_throw_rate (nullable) is None
        # and __fields_set__ contains the field
        if self.free_throw_rate is None and "free_throw_rate" in self.__fields_set__:
            _dict['freeThrowRate'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TeamStatsLeaderboardUnitStats:
        """Create an instance of TeamStatsLeaderboardUnitStats from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TeamStatsLeaderboardUnitStats.parse_obj(obj)

        _obj = TeamStatsLeaderboardUnitStats.parse_obj({
            "points": TeamStatsLeaderboardUnitStatsPoints.from_dict(obj.get("points")) if obj.get("points") is not None else None,
            "possessions": obj.get("possessions"),
            "raw_offensive_rating": obj.get("rawOffensiveRating"),
            "true_shooting_pct": obj.get("trueShootingPct"),
            "effective_field_goal_pct": obj.get("effectiveFieldGoalPct"),
            "turnover_ratio": obj.get("turnoverRatio"),
            "offensive_rebound_pct": obj.get("offensiveReboundPct"),
            "free_throw_rate": obj.get("freeThrowRate"),
            "field_goals": TeamStatsLeaderboardUnitStatsFieldGoals.from_dict(obj.get("fieldGoals")) if obj.get("fieldGoals") is not None else None,
            "two_point_field_goals": TeamStatsLeaderboardUnitStatsFieldGoals.from_dict(obj.get("twoPointFieldGoals")) if obj.get("twoPointFieldGoals") is not None else None,
            "three_point_field_goals": TeamStatsLeaderboardUnitStatsFieldGoals.from_dict(obj.get("threePointFieldGoals")) if obj.get("threePointFieldGoals") is not None else None,
            "free_throws": TeamStatsLeaderboardUnitStatsFieldGoals.from_dict(obj.get("freeThrows")) if obj.get("freeThrows") is not None else None,
            "rebounds": TeamStatsLeaderboardUnitStatsRebounds.from_dict(obj.get("rebounds")) if obj.get("rebounds") is not None else None,
            "turnovers": TeamStatsLeaderboardUnitStatsTurnovers.from_dict(obj.get("turnovers")) if obj.get("turnovers") is not None else None,
            "fouls": TeamStatsLeaderboardUnitStatsFouls.from_dict(obj.get("fouls")) if obj.get("fouls") is not None else None,
            "assists": obj.get("assists"),
            "blocks": obj.get("blocks"),
            "steals": obj.get("steals")
        })
        return _obj


