# coding: utf-8

"""
    College Basketball Data API

    Use the College Basketball Data API to query game, team, player, recruiting, and analytics data. Request an API key at [CollegeBasketballData.com](https://collegebasketballdata.com/key).

    The version of the OpenAPI document: 1.30.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt, StrictStr, validator
from cbbd.models.team_season_overview_efficiency import TeamSeasonOverviewEfficiency
from cbbd.models.team_season_overview_players import TeamSeasonOverviewPlayers
from cbbd.models.team_season_overview_ratings import TeamSeasonOverviewRatings
from cbbd.models.team_season_overview_record import TeamSeasonOverviewRecord
from cbbd.models.team_season_overview_schedule import TeamSeasonOverviewSchedule
from cbbd.models.team_season_overview_shooting import TeamSeasonOverviewShooting
from cbbd.models.team_season_overview_sources import TeamSeasonOverviewSources
from cbbd.models.team_season_overview_team import TeamSeasonOverviewTeam

class TeamSeasonOverview(BaseModel):
    """
    TeamSeasonOverview
    """
    format_version: Union[StrictFloat, StrictInt] = Field(default=..., alias="formatVersion")
    team_id: Union[StrictFloat, StrictInt] = Field(default=..., alias="teamId")
    season: Union[StrictFloat, StrictInt] = Field(...)
    season_label: StrictStr = Field(default=..., alias="seasonLabel")
    generated_at: StrictStr = Field(default=..., alias="generatedAt")
    team: TeamSeasonOverviewTeam = Field(...)
    record: TeamSeasonOverviewRecord = Field(...)
    ratings: TeamSeasonOverviewRatings = Field(...)
    efficiency: TeamSeasonOverviewEfficiency = Field(...)
    shooting: TeamSeasonOverviewShooting = Field(...)
    players: TeamSeasonOverviewPlayers = Field(...)
    schedule: TeamSeasonOverviewSchedule = Field(...)
    sources: TeamSeasonOverviewSources = Field(...)
    __properties = ["formatVersion", "teamId", "season", "seasonLabel", "generatedAt", "team", "record", "ratings", "efficiency", "shooting", "players", "schedule", "sources"]

    @validator('format_version')
    def format_version_validate_enum(cls, value):
        """Validates the enum"""
        if value not in (1, 2,):
            raise ValueError("must be one of enum values (1, 2)")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TeamSeasonOverview:
        """Create an instance of TeamSeasonOverview from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of team
        if self.team:
            _dict['team'] = self.team.to_dict()
        # override the default output from pydantic by calling `to_dict()` of record
        if self.record:
            _dict['record'] = self.record.to_dict()
        # override the default output from pydantic by calling `to_dict()` of ratings
        if self.ratings:
            _dict['ratings'] = self.ratings.to_dict()
        # override the default output from pydantic by calling `to_dict()` of efficiency
        if self.efficiency:
            _dict['efficiency'] = self.efficiency.to_dict()
        # override the default output from pydantic by calling `to_dict()` of shooting
        if self.shooting:
            _dict['shooting'] = self.shooting.to_dict()
        # override the default output from pydantic by calling `to_dict()` of players
        if self.players:
            _dict['players'] = self.players.to_dict()
        # override the default output from pydantic by calling `to_dict()` of schedule
        if self.schedule:
            _dict['schedule'] = self.schedule.to_dict()
        # override the default output from pydantic by calling `to_dict()` of sources
        if self.sources:
            _dict['sources'] = self.sources.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TeamSeasonOverview:
        """Create an instance of TeamSeasonOverview from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TeamSeasonOverview.parse_obj(obj)

        _obj = TeamSeasonOverview.parse_obj({
            "format_version": obj.get("formatVersion"),
            "team_id": obj.get("teamId"),
            "season": obj.get("season"),
            "season_label": obj.get("seasonLabel"),
            "generated_at": obj.get("generatedAt"),
            "team": TeamSeasonOverviewTeam.from_dict(obj.get("team")) if obj.get("team") is not None else None,
            "record": TeamSeasonOverviewRecord.from_dict(obj.get("record")) if obj.get("record") is not None else None,
            "ratings": TeamSeasonOverviewRatings.from_dict(obj.get("ratings")) if obj.get("ratings") is not None else None,
            "efficiency": TeamSeasonOverviewEfficiency.from_dict(obj.get("efficiency")) if obj.get("efficiency") is not None else None,
            "shooting": TeamSeasonOverviewShooting.from_dict(obj.get("shooting")) if obj.get("shooting") is not None else None,
            "players": TeamSeasonOverviewPlayers.from_dict(obj.get("players")) if obj.get("players") is not None else None,
            "schedule": TeamSeasonOverviewSchedule.from_dict(obj.get("schedule")) if obj.get("schedule") is not None else None,
            "sources": TeamSeasonOverviewSources.from_dict(obj.get("sources")) if obj.get("sources") is not None else None
        })
        return _obj


