# coding: utf-8

"""
    College Basketball Data API

    Use the College Basketball Data API to query game, team, player, recruiting, and analytics data. Request an API key at [CollegeBasketballData.com](https://collegebasketballdata.com/key).

    The version of the OpenAPI document: 1.30.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List
from pydantic import BaseModel, Field, conlist
from cbbd.models.profile_game import ProfileGame

class TeamSeasonOverviewSchedule(BaseModel):
    """
    TeamSeasonOverviewSchedule
    """
    games: conlist(ProfileGame) = Field(...)
    __properties = ["games"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TeamSeasonOverviewSchedule:
        """Create an instance of TeamSeasonOverviewSchedule from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in games (list)
        _items = []
        if self.games:
            for _item in self.games:
                if _item:
                    _items.append(_item.to_dict())
            _dict['games'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TeamSeasonOverviewSchedule:
        """Create an instance of TeamSeasonOverviewSchedule from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TeamSeasonOverviewSchedule.parse_obj(obj)

        _obj = TeamSeasonOverviewSchedule.parse_obj({
            "games": [ProfileGame.from_dict(_item) for _item in obj.get("games")] if obj.get("games") is not None else None
        })
        return _obj


