# coding: utf-8

"""
    College Basketball Data API

    Use the College Basketball Data API to query game, team, player, recruiting, and analytics data. Request an API key at [CollegeBasketballData.com](https://collegebasketballdata.com/key).

    The version of the OpenAPI document: 1.29.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt, conlist
from cbbd.models.coverage import Coverage
from cbbd.models.shot_bucket import ShotBucket

class TeamSeasonOverviewShooting(BaseModel):
    """
    TeamSeasonOverviewShooting
    """
    buckets: conlist(ShotBucket) = Field(...)
    tracked_attempts: Union[StrictFloat, StrictInt] = Field(default=..., alias="trackedAttempts")
    coverage: Coverage = Field(...)
    __properties = ["buckets", "trackedAttempts", "coverage"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TeamSeasonOverviewShooting:
        """Create an instance of TeamSeasonOverviewShooting from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in buckets (list)
        _items = []
        if self.buckets:
            for _item in self.buckets:
                if _item:
                    _items.append(_item.to_dict())
            _dict['buckets'] = _items
        # override the default output from pydantic by calling `to_dict()` of coverage
        if self.coverage:
            _dict['coverage'] = self.coverage.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TeamSeasonOverviewShooting:
        """Create an instance of TeamSeasonOverviewShooting from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TeamSeasonOverviewShooting.parse_obj(obj)

        _obj = TeamSeasonOverviewShooting.parse_obj({
            "buckets": [ShotBucket.from_dict(_item) for _item in obj.get("buckets")] if obj.get("buckets") is not None else None,
            "tracked_attempts": obj.get("trackedAttempts"),
            "coverage": Coverage.from_dict(obj.get("coverage")) if obj.get("coverage") is not None else None
        })
        return _obj


