# coding: utf-8

"""
    College Basketball Data API

    This is an API for query various college basketball datasets and analytics. API keys can be acquired by registering on the CollegeBasketballData.com website.

    The version of the OpenAPI document: 1.27.3
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt
from cbbd.models.team_leaderboard_adjusted_efficiency_rankings import TeamLeaderboardAdjustedEfficiencyRankings

class TeamLeaderboardAdjustedEfficiency(BaseModel):
    """
    TeamLeaderboardAdjustedEfficiency
    """
    offensive_rating: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="offensiveRating")
    defensive_rating: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="defensiveRating")
    net_rating: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="netRating")
    rankings: TeamLeaderboardAdjustedEfficiencyRankings = Field(...)
    __properties = ["offensiveRating", "defensiveRating", "netRating", "rankings"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TeamLeaderboardAdjustedEfficiency:
        """Create an instance of TeamLeaderboardAdjustedEfficiency from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of rankings
        if self.rankings:
            _dict['rankings'] = self.rankings.to_dict()
        # set to None if offensive_rating (nullable) is None
        # and __fields_set__ contains the field
        if self.offensive_rating is None and "offensive_rating" in self.__fields_set__:
            _dict['offensiveRating'] = None

        # set to None if defensive_rating (nullable) is None
        # and __fields_set__ contains the field
        if self.defensive_rating is None and "defensive_rating" in self.__fields_set__:
            _dict['defensiveRating'] = None

        # set to None if net_rating (nullable) is None
        # and __fields_set__ contains the field
        if self.net_rating is None and "net_rating" in self.__fields_set__:
            _dict['netRating'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TeamLeaderboardAdjustedEfficiency:
        """Create an instance of TeamLeaderboardAdjustedEfficiency from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TeamLeaderboardAdjustedEfficiency.parse_obj(obj)

        _obj = TeamLeaderboardAdjustedEfficiency.parse_obj({
            "offensive_rating": obj.get("offensiveRating"),
            "defensive_rating": obj.get("defensiveRating"),
            "net_rating": obj.get("netRating"),
            "rankings": TeamLeaderboardAdjustedEfficiencyRankings.from_dict(obj.get("rankings")) if obj.get("rankings") is not None else None
        })
        return _obj


