# coding: utf-8

"""
    College Basketball Data API

    Use the College Basketball Data API to query game, team, player, recruiting, and analytics data. Request an API key at [CollegeBasketballData.com](https://collegebasketballdata.com/key).

    The version of the OpenAPI document: 1.30.1
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt
from cbbd.models.shooting_line import ShootingLine
from cbbd.models.team_box_score_rebounds import TeamBoxScoreRebounds

class TeamBoxScore(BaseModel):
    """
    TeamBoxScore
    """
    field_goals: ShootingLine = Field(default=..., alias="fieldGoals")
    two_point_field_goals: ShootingLine = Field(default=..., alias="twoPointFieldGoals")
    three_point_field_goals: ShootingLine = Field(default=..., alias="threePointFieldGoals")
    free_throws: ShootingLine = Field(default=..., alias="freeThrows")
    rebounds: TeamBoxScoreRebounds = Field(...)
    assists: Optional[Union[StrictFloat, StrictInt]] = Field(...)
    steals: Optional[Union[StrictFloat, StrictInt]] = Field(...)
    blocks: Optional[Union[StrictFloat, StrictInt]] = Field(...)
    turnovers: Optional[Union[StrictFloat, StrictInt]] = Field(...)
    fouls: Optional[Union[StrictFloat, StrictInt]] = Field(...)
    minutes: Optional[Union[StrictFloat, StrictInt]] = Field(...)
    team_turnovers: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="teamTurnovers")
    technical_fouls: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="technicalFouls")
    flagrant_fouls: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="flagrantFouls")
    points_in_paint: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="pointsInPaint")
    points_off_turnovers: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="pointsOffTurnovers")
    fast_break_points: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="fastBreakPoints")
    true_shooting_pct: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="trueShootingPct")
    __properties = ["fieldGoals", "twoPointFieldGoals", "threePointFieldGoals", "freeThrows", "rebounds", "assists", "steals", "blocks", "turnovers", "fouls", "minutes", "teamTurnovers", "technicalFouls", "flagrantFouls", "pointsInPaint", "pointsOffTurnovers", "fastBreakPoints", "trueShootingPct"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TeamBoxScore:
        """Create an instance of TeamBoxScore from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of field_goals
        if self.field_goals:
            _dict['fieldGoals'] = self.field_goals.to_dict()
        # override the default output from pydantic by calling `to_dict()` of two_point_field_goals
        if self.two_point_field_goals:
            _dict['twoPointFieldGoals'] = self.two_point_field_goals.to_dict()
        # override the default output from pydantic by calling `to_dict()` of three_point_field_goals
        if self.three_point_field_goals:
            _dict['threePointFieldGoals'] = self.three_point_field_goals.to_dict()
        # override the default output from pydantic by calling `to_dict()` of free_throws
        if self.free_throws:
            _dict['freeThrows'] = self.free_throws.to_dict()
        # override the default output from pydantic by calling `to_dict()` of rebounds
        if self.rebounds:
            _dict['rebounds'] = self.rebounds.to_dict()
        # set to None if assists (nullable) is None
        # and __fields_set__ contains the field
        if self.assists is None and "assists" in self.__fields_set__:
            _dict['assists'] = None

        # set to None if steals (nullable) is None
        # and __fields_set__ contains the field
        if self.steals is None and "steals" in self.__fields_set__:
            _dict['steals'] = None

        # set to None if blocks (nullable) is None
        # and __fields_set__ contains the field
        if self.blocks is None and "blocks" in self.__fields_set__:
            _dict['blocks'] = None

        # set to None if turnovers (nullable) is None
        # and __fields_set__ contains the field
        if self.turnovers is None and "turnovers" in self.__fields_set__:
            _dict['turnovers'] = None

        # set to None if fouls (nullable) is None
        # and __fields_set__ contains the field
        if self.fouls is None and "fouls" in self.__fields_set__:
            _dict['fouls'] = None

        # set to None if minutes (nullable) is None
        # and __fields_set__ contains the field
        if self.minutes is None and "minutes" in self.__fields_set__:
            _dict['minutes'] = None

        # set to None if team_turnovers (nullable) is None
        # and __fields_set__ contains the field
        if self.team_turnovers is None and "team_turnovers" in self.__fields_set__:
            _dict['teamTurnovers'] = None

        # set to None if technical_fouls (nullable) is None
        # and __fields_set__ contains the field
        if self.technical_fouls is None and "technical_fouls" in self.__fields_set__:
            _dict['technicalFouls'] = None

        # set to None if flagrant_fouls (nullable) is None
        # and __fields_set__ contains the field
        if self.flagrant_fouls is None and "flagrant_fouls" in self.__fields_set__:
            _dict['flagrantFouls'] = None

        # set to None if points_in_paint (nullable) is None
        # and __fields_set__ contains the field
        if self.points_in_paint is None and "points_in_paint" in self.__fields_set__:
            _dict['pointsInPaint'] = None

        # set to None if points_off_turnovers (nullable) is None
        # and __fields_set__ contains the field
        if self.points_off_turnovers is None and "points_off_turnovers" in self.__fields_set__:
            _dict['pointsOffTurnovers'] = None

        # set to None if fast_break_points (nullable) is None
        # and __fields_set__ contains the field
        if self.fast_break_points is None and "fast_break_points" in self.__fields_set__:
            _dict['fastBreakPoints'] = None

        # set to None if true_shooting_pct (nullable) is None
        # and __fields_set__ contains the field
        if self.true_shooting_pct is None and "true_shooting_pct" in self.__fields_set__:
            _dict['trueShootingPct'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TeamBoxScore:
        """Create an instance of TeamBoxScore from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TeamBoxScore.parse_obj(obj)

        _obj = TeamBoxScore.parse_obj({
            "field_goals": ShootingLine.from_dict(obj.get("fieldGoals")) if obj.get("fieldGoals") is not None else None,
            "two_point_field_goals": ShootingLine.from_dict(obj.get("twoPointFieldGoals")) if obj.get("twoPointFieldGoals") is not None else None,
            "three_point_field_goals": ShootingLine.from_dict(obj.get("threePointFieldGoals")) if obj.get("threePointFieldGoals") is not None else None,
            "free_throws": ShootingLine.from_dict(obj.get("freeThrows")) if obj.get("freeThrows") is not None else None,
            "rebounds": TeamBoxScoreRebounds.from_dict(obj.get("rebounds")) if obj.get("rebounds") is not None else None,
            "assists": obj.get("assists"),
            "steals": obj.get("steals"),
            "blocks": obj.get("blocks"),
            "turnovers": obj.get("turnovers"),
            "fouls": obj.get("fouls"),
            "minutes": obj.get("minutes"),
            "team_turnovers": obj.get("teamTurnovers"),
            "technical_fouls": obj.get("technicalFouls"),
            "flagrant_fouls": obj.get("flagrantFouls"),
            "points_in_paint": obj.get("pointsInPaint"),
            "points_off_turnovers": obj.get("pointsOffTurnovers"),
            "fast_break_points": obj.get("fastBreakPoints"),
            "true_shooting_pct": obj.get("trueShootingPct")
        })
        return _obj


