# coding: utf-8

"""
    College Basketball Data API

    This is an API for query various college basketball datasets and analytics. API keys can be acquired by registering on the CollegeBasketballData.com website.

    The version of the OpenAPI document: 1.27.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt, StrictStr
from cbbd.models.recruit_committed_to import RecruitCommittedTo
from cbbd.models.transfer_eligibility import TransferEligibility
from cbbd.models.transfer_origin import TransferOrigin

class Transfer(BaseModel):
    """
    Transfer
    """
    id: StrictInt = Field(...)
    source_id: StrictStr = Field(default=..., alias="sourceId")
    year: StrictInt = Field(...)
    first_name: StrictStr = Field(default=..., alias="firstName")
    last_name: StrictStr = Field(default=..., alias="lastName")
    position: StrictStr = Field(...)
    origin: Optional[TransferOrigin] = Field(...)
    destination: Optional[RecruitCommittedTo] = Field(...)
    eligibility: Optional[TransferEligibility] = Field(...)
    years_remaining: Optional[StrictInt] = Field(default=..., alias="yearsRemaining")
    stars: Optional[StrictInt] = Field(...)
    rating: Optional[Union[StrictFloat, StrictInt]] = Field(...)
    __properties = ["id", "sourceId", "year", "firstName", "lastName", "position", "origin", "destination", "eligibility", "yearsRemaining", "stars", "rating"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Transfer:
        """Create an instance of Transfer from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of origin
        if self.origin:
            _dict['origin'] = self.origin.to_dict()
        # override the default output from pydantic by calling `to_dict()` of destination
        if self.destination:
            _dict['destination'] = self.destination.to_dict()
        # set to None if origin (nullable) is None
        # and __fields_set__ contains the field
        if self.origin is None and "origin" in self.__fields_set__:
            _dict['origin'] = None

        # set to None if destination (nullable) is None
        # and __fields_set__ contains the field
        if self.destination is None and "destination" in self.__fields_set__:
            _dict['destination'] = None

        # set to None if eligibility (nullable) is None
        # and __fields_set__ contains the field
        if self.eligibility is None and "eligibility" in self.__fields_set__:
            _dict['eligibility'] = None

        # set to None if years_remaining (nullable) is None
        # and __fields_set__ contains the field
        if self.years_remaining is None and "years_remaining" in self.__fields_set__:
            _dict['yearsRemaining'] = None

        # set to None if stars (nullable) is None
        # and __fields_set__ contains the field
        if self.stars is None and "stars" in self.__fields_set__:
            _dict['stars'] = None

        # set to None if rating (nullable) is None
        # and __fields_set__ contains the field
        if self.rating is None and "rating" in self.__fields_set__:
            _dict['rating'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Transfer:
        """Create an instance of Transfer from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Transfer.parse_obj(obj)

        _obj = Transfer.parse_obj({
            "id": obj.get("id"),
            "source_id": obj.get("sourceId"),
            "year": obj.get("year"),
            "first_name": obj.get("firstName"),
            "last_name": obj.get("lastName"),
            "position": obj.get("position"),
            "origin": TransferOrigin.from_dict(obj.get("origin")) if obj.get("origin") is not None else None,
            "destination": RecruitCommittedTo.from_dict(obj.get("destination")) if obj.get("destination") is not None else None,
            "eligibility": obj.get("eligibility"),
            "years_remaining": obj.get("yearsRemaining"),
            "stars": obj.get("stars"),
            "rating": obj.get("rating")
        })
        return _obj


