# coding: utf-8

"""
    College Basketball Data API

    Use the College Basketball Data API to query game, team, player, recruiting, and analytics data. Request an API key at [CollegeBasketballData.com](https://collegebasketballdata.com/key).

    The version of the OpenAPI document: 1.29.0
    Contact: admin@collegefootballdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt
from cbbd.models.team_box_score import TeamBoxScore

class UnitMetrics(BaseModel):
    """
    UnitMetrics
    """
    box_score: Optional[TeamBoxScore] = Field(default=None, alias="boxScore")
    points: Optional[Union[StrictFloat, StrictInt]] = Field(...)
    possessions: Optional[Union[StrictFloat, StrictInt]] = Field(...)
    raw_rating: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="rawRating")
    effective_field_goal_pct: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="effectiveFieldGoalPct")
    turnover_pct: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="turnoverPct")
    offensive_rebound_pct: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="offensiveReboundPct")
    free_throw_rate: Optional[Union[StrictFloat, StrictInt]] = Field(default=..., alias="freeThrowRate")
    __properties = ["boxScore", "points", "possessions", "rawRating", "effectiveFieldGoalPct", "turnoverPct", "offensiveReboundPct", "freeThrowRate"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> UnitMetrics:
        """Create an instance of UnitMetrics from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of box_score
        if self.box_score:
            _dict['boxScore'] = self.box_score.to_dict()
        # set to None if points (nullable) is None
        # and __fields_set__ contains the field
        if self.points is None and "points" in self.__fields_set__:
            _dict['points'] = None

        # set to None if possessions (nullable) is None
        # and __fields_set__ contains the field
        if self.possessions is None and "possessions" in self.__fields_set__:
            _dict['possessions'] = None

        # set to None if raw_rating (nullable) is None
        # and __fields_set__ contains the field
        if self.raw_rating is None and "raw_rating" in self.__fields_set__:
            _dict['rawRating'] = None

        # set to None if effective_field_goal_pct (nullable) is None
        # and __fields_set__ contains the field
        if self.effective_field_goal_pct is None and "effective_field_goal_pct" in self.__fields_set__:
            _dict['effectiveFieldGoalPct'] = None

        # set to None if turnover_pct (nullable) is None
        # and __fields_set__ contains the field
        if self.turnover_pct is None and "turnover_pct" in self.__fields_set__:
            _dict['turnoverPct'] = None

        # set to None if offensive_rebound_pct (nullable) is None
        # and __fields_set__ contains the field
        if self.offensive_rebound_pct is None and "offensive_rebound_pct" in self.__fields_set__:
            _dict['offensiveReboundPct'] = None

        # set to None if free_throw_rate (nullable) is None
        # and __fields_set__ contains the field
        if self.free_throw_rate is None and "free_throw_rate" in self.__fields_set__:
            _dict['freeThrowRate'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> UnitMetrics:
        """Create an instance of UnitMetrics from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return UnitMetrics.parse_obj(obj)

        _obj = UnitMetrics.parse_obj({
            "box_score": TeamBoxScore.from_dict(obj.get("boxScore")) if obj.get("boxScore") is not None else None,
            "points": obj.get("points"),
            "possessions": obj.get("possessions"),
            "raw_rating": obj.get("rawRating"),
            "effective_field_goal_pct": obj.get("effectiveFieldGoalPct"),
            "turnover_pct": obj.get("turnoverPct"),
            "offensive_rebound_pct": obj.get("offensiveReboundPct"),
            "free_throw_rate": obj.get("freeThrowRate")
        })
        return _obj


